### ISSUE TITLE
Artist was ignored

### ISSUE THREAD

**Issue by MissingNumb3r** [kawaiiDango/pScrobbler#1]
"Artist xyz was ignored" notification, scrobble function doesn't work, even though everything is enabled and has worked before with same apps.

**Comment by MissingNumb3r** [comment]
Specs: Pano Scrobbler v0.54 - 12.Dec.17
Android 7.0
ROM: NEM-L51C432B350
Device: HONOR NEM-L51
RAM: 1781M 
Screen: 1080 x 1812,  480 DPI

**Comment by kawaiiDango** [comment]
Which artist was that? 

Btw that message means that the app submitted the scrobble, but lastfm responded by saying it was ignored. 

https://www.last.fm/api/show/track.scrobble has an **accepted** and **ignored** response fields and there's no documentation about what causes it to ignore

**Comment by kawaiiDango** [comment]
- Changed the message to blame last.fm instead of the artist, since this is a server side thing
- Omit "unknown" as album names - they get ignored otherwise
