### ISSUE TITLE
Artist name with semicolon cut

### ISSUE THREAD

**Issue by fimzoak** [kawaiiDango/pScrobbler#10]
The artist Sophiaaaahjkl;8901 (artist page https://www.last.fm/music/Sophiaaaahjkl;8901) incorrectly scrobbles as "Sophiaaaahjkl". It looks like this related to closed issue #4...

**Comment by kawaiiDango** [comment]
I changed the seperator to "; "

**Comment by fimzoak** [comment]
Seems to have fixed it, ty!
