### ISSUE TITLE
Scrobbling on repeat

### ISSUE THREAD

**Issue by Nowena** [kawaiiDango/pScrobbler#100]
The app does not scrobble songs on repeat every time, only submits the first one.
Can this be fixed please?

**Comment by kawaiiDango** [comment]
Works fine here with youtube

**Comment by Nowena** [comment]
I am scrobbling from blackplayer ex

**Comment by kawaiiDango** [comment]
Blackplayer doesn't send any repeat events

**Comment by Nowena** [comment]
I was using shuttle music player and media monkey before but switched to blackplayer ex cuz shuttle and monkey mess up some special characters and scrobbles em wrong (for example tool's ænima is ćnima). 

Blackplayer is literally the only music player that doesn't do this and I tried a lot of them so there's nothing I can use instead.

Guess I cannot listen to anything on repeat now then.
