### ISSUE TITLE
Cannot load the cover pictures

### ISSUE THREAD

**Issue by ikuya2015** [kawaiiDango/pScrobbler#101]
I updated pano from v1.63 to the latest version a few days ago and found that I couldn't see the album covers anymore. After days of useless trying I uninstalled the latest version and installed v1.63 again but the cover photos still haven't come back. Could you please tell me what's gone wrong? Thx a lot.

**Comment by kawaiiDango** [comment]
Network or disk issue. Got nothing to do with the app.

**Comment by bryanbuty** [comment]
I also have the same problem eventhough the lastfm APP cover works just fine, any ideas?

**Comment by ikuya2015** [comment]
I've recently found that the artist pictures can be loaded normally, but the covers still can't...

**Comment by ikuya2015** [comment]
> I also have the same problem eventhough the lastfm APP cover works just fine, any ideas?

I've recently found that the artist pictures can be loaded normally, but the covers still can't...

**Comment by bryanbuty** [comment]
Oh, okay. Thank you for answering.

**Comment by kawaiiDango** [comment]
Updated a very old version of okhttp that was not fully compatible with Android 11. Check if this issue still happens on v2.7 after Google has approved my update.
