### ISSUE TITLE
[Feature Request] Sync like/dislike from streaming services

### ISSUE THREAD

**Issue by schradert** [kawaiiDango/pScrobbler#102]
It would be nice to automatically like a scrobbled song in Pano if it has already been liked on the service the song was scrobbled from. This mostly only applies for common streaming services, but since these make up most of my listening history, it would prevent me from having to constantly press multiple buttons. This could be a togglable setting for those who wouldn't want this.

**Comment by kawaiiDango** [comment]
This is a pretty broad statement and would require spamming the lastfm api if it was even feasible
