### ISSUE TITLE
Problem with Album Artist Passed on Pandora

### ISSUE THREAD

**Issue by El-Motu** [kawaiiDango/pScrobbler#104]
Hello,

am able to scrobble from Pandora but the album artwork is not coming through, the art DOES show on now playing but once the song is done and goes to my list the album art is gone.

When clicking on the song on my scrobbles the track DOES have an album linked to it, and the art shows on the album, just the recent track view seems to be off.

![3E341D94-AB1E-4DFD-9A70-C23ACFA975C1](https://user-images.githubusercontent.com/74815525/99874368-55ac7900-2bdf-11eb-9e12-b46c1c8568ed.jpeg)

The problem lies in the album artist field uploaded form the scrobbler, for the example above, it is showing this in the Album Artist field:
“Whitley - The Submarine”
Sot he scrobbler is passing the artist AND the track as the album artist in this format as the
Album Artist:
“Artist - Track”
This in turn makes the album art fail.

Form my post below I got this response: _“the album artist field. That's why your tags are screwed up. Check the ID3 tags for all albums that you are listening to. There might be more of them that need to be corrected. Since you are a subscriber, it won't be hard for you to fix it. Update: I was right. You have incoherent tags in your library.”_

https://support.last.fm/t/no-album-art-from-pandora/21027

So far no scrobbler can fix the album artist issue from Pandora BEFORE uploading, seems like a simple fix (or maybe give us the option of what fields we want to upload, the reason why the album art works when playing is because the field ‘album artist’ is not passed as the corrupted value from Pandora on the ‘now playing view’ so the track and artist are auto mapped, however once the upload happens then the ‘album artist’ is uploaded with the wrong value sent from Pandora messing things up.

Any fix on the next release would be ACE!

Thanks!

**Comment by kawaiiDango** [comment]
> Album Artist:
> “Artist - Track”
> This in turn makes the album art fail.

Thats wrong. I just checked, Pandora passes "Artist - Album" as the album artist because they think that album artist = album + artist lmao. Will add an exception for Pandora to remove the album artist in the next update.

**Comment by El-Motu** [comment]
> > Album Artist:
> > “Artist - Track”
> > This in turn makes the album art fail.
> 
> Thats wrong. I just checked, Pandora passes "Artist - Album" as the album artist because they think that album artist = album + artist lmao. Will add an exception for Pandora to remove the album artist in the next update.

Yay thanks! I’ll keep an eye out on the store for updates! 😎🤙
