### ISSUE TITLE
Auto-generated songs on YouTube scrobble incorrectly.

### ISSUE THREAD

**Issue by arm32x** [kawaiiDango/pScrobbler#106]
When listening to a song on YouTube (not YouTube Music) that was auto-generated by YouTube, the title is chosen as the artist.

Here is an example: https://youtu.be/sj3w0UsmXMc.

**Comment by kawaiiDango** [comment]
The title needs to be in artist - title or similar formats, otherwise we
don't know whether it is an artist or title or both
