### ISSUE TITLE
Wrong information taken for "Artist"

### ISSUE THREAD

**Issue by Staubsaugerbeutel** [kawaiiDango/pScrobbler#11]
As you can see, the app takes the name of the radio station "Fip Rock" as the artist instead of the Stones which are also in the information. I can edit the scrobble but instead of doing it every time, a feature letting us edit which information is taken for which category (for each app) would be quite helpful.
The music app is the fip radio app.

![](https://cdn.discordapp.com/attachments/339827342266466306/497308485126717440/Screenshot_20181004-092538_1.jpg)

**Comment by kawaiiDango** [comment]
The player is sending wrong metadata
