### ISSUE TITLE
[Feature Request] Auto correct scrobbles

### ISSUE THREAD

**Issue by okarin001** [kawaiiDango/pScrobbler#114]
I am trying to move from Spotify to apple music. I was using this app only to scrobble for local music because of Spotify's lastFM integration. But with apple music, I had to use this app. This app is working great. I have just one simple suggestion.

### Feature Request

When using Spotify if I listen to a Japanese artist with a romaji name the name would auto-correct itself to its original form.

 An example:
 - Apple and Spotify both plays [松任谷由実][1] as [Yumi Matsutouya][2] 
 - While using Spotify's native scrobbling LastFM autocorrects it to the real artist page [松任谷由実][1].
- In Apple Music while using your app this doesn't happen. It stays to [Yumi Matsutouya][2]

So, by any chance, you can **add something in your app** so that **apple music can automatically** do this instead of me changing the names manually. 

[1]: https://www.last.fm/music/%E6%9D%BE%E4%BB%BB%E8%B0%B7%E7%94%B1%E5%AE%9F
[2]: https://www.last.fm/music/Yumi+Matsutouya

**Comment by kawaiiDango** [comment]
Scrobblers don't autocorrect data. It is up to the the players and web services to put the correct data
