### ISSUE TITLE
Add Support for Digitally Imported Radio

### ISSUE THREAD

**Issue by bgiesing** [kawaiiDango/pScrobbler#115]
https://play.google.com/store/apps/details?id=com.audioaddict.di

Notification shows up as:

> Station Name
> Artist - Song

So it tracks improperly when added as other.

**Comment by kawaiiDango** [comment]
https://github.com/kawaiiDango/pScrobbler/commit/3c10540195ac269a7853bcb2a8a1a1997923055d
