### ISSUE TITLE
Add support for Eggs.mu app

### ISSUE THREAD

**Issue by yayuyokitano** [kawaiiDango/pScrobbler#117]
Eggs seems to be using some custom notification layout that messes with pano.
Currently unable to scrobble even after checking eggs under "other apps".
It's region locked to japan, so here's apk https://drive.google.com/file/d/16aRhBo-D2OdVBprALeGBfpjtFWDpd5Ds/view?usp=drivesdk
Used the apk extractor by meher for this, so if you don't trust that then let me know what extractor to use and I can do.
You should be able to log in as guest in the bottom right.
Hopefully it is workable.

**Comment by kawaiiDango** [comment]
It is not possible to scrobble that app as it does not reveal any metadata. Also, pano does not read any notifications

**Comment by yayuyokitano** [comment]
Ah I see, that is unfortunate.
Thanks for checking it out anyway!
