### ISSUE TITLE
Scrobbles from YouTube when app not enabled 

### ISSUE THREAD

**Issue by condwanaland** [kawaiiDango/pScrobbler#122]
I have Pano set to scrobble from YouTube music app, but not from YouTube. However, when playing videos on YouTube, it still seems to try scrobble them.

This is what's shown when playing a video
![Screenshot_20210320-161118_YouTube](https://user-images.githubusercontent.com/23396385/111857577-51c71280-8997-11eb-91c3-fbdd8ad3125b.jpg)

These are my settings
![Screenshot_20210320-161137_Pano Scrobbler](https://user-images.githubusercontent.com/23396385/111857580-5be91100-8997-11eb-866e-0c1b4198cdb5.jpg)
![Screenshot_20210320-161147_Pano Scrobbler](https://user-images.githubusercontent.com/23396385/111857583-60adc500-8997-11eb-8c85-79023fdf2aff.jpg)

**Comment by kawaiiDango** [comment]
Does this fix itself after a reboot? Does this always happen or just sometimes?

**Comment by condwanaland** [comment]
This seems to have resolved itself after a reboot.

**Comment by kawaiiDango** [comment]
Have you rated the app? This might have something to do with the rating prompt

**Comment by SuchaComic** [comment]
Deleting the review fr play store did solve the issue. No unwanted Youtube scrobbles since then.
