### ISSUE TITLE
Offline scrobbles

### ISSUE THREAD

**Issue by Nowena** [kawaiiDango/pScrobbler#124]
For a while now, I noticed the app hasn't been storing/saving offline plays to later submit to last.fm as it had been in the past.

Can you please fix this? It's very important. Every scrobble counts haha

**Comment by kawaiiDango** [comment]
When was the last time it worked?

**Comment by Nowena** [comment]
Last week, I think. Also, I cannot delete scrobbles using the app anymore. Have to go to last.fm and do it there

**Comment by kawaiiDango** [comment]
The code for offline scrobbles hasn't changed in half a year so it is something else. The code for deleting scrobbles also hasn't changed in a long time.

**Comment by Nowena** [comment]
So what could it be? Do offline scrobbling and deleting scrobbles work for you?

**Comment by kawaiiDango** [comment]
Both of them are working for me.
It could be a network error, lastfm authentication error, lastfm cookies getting expired, your OS killing the scrobbler when in background, or something else. You could try logging out and logging in and check dontkillmyapp.com

**Comment by Nowena** [comment]
It worked for deleting scrobbles but it still won't scrobble offline.

**Comment by Nowena** [comment]
When I listen to something offline, pano says it scrobbled then when I connect to the internet again, it's never submitted and nowhere to be seen.

After the first time I logged out then in again on the app, I got a notification with something saying 'unable to connect' to ws.something. Didn't take a screenshot before dismissing it tho :/

**Comment by Nowena** [comment]
Purged cookies, checked battery settings and my os isn't killing the app in background.

Still won't work, idk what else to try. I didn't change anything on my phone, it was working fine last week

**Comment by kawaiiDango** [comment]
If you are still having this, please send a bug report from the app shortly after it happens. It is pretty hard to track bugs which are not reproducible since the app does not contain any tracking libraries like crashlytics

**Comment by Nowena** [comment]
Hi, I found the problem was I had the 'data' option on (turned it on when I was out one day and forgot to turning off) and I had no data to use anymore when not connected to wifi so that was preventing pano from submitting offline scrobbles correctly.

**Comment by kawaiiDango** [comment]
Which phone and Android version do you have?

**Comment by Nowena** [comment]
I have a moto g(7) and android 10

**Comment by Nowena** [comment]
No, still not submitting scrobbles

**Comment by kawaiiDango** [comment]
Check if v2.12 has fixed this issue

**Comment by Nowena** [comment]
all good, thank you
