### ISSUE TITLE
Many artists not recognized,

### ISSUE THREAD

**Issue by christubuntu** [kawaiiDango/pScrobbler#126]
I have an issue where Pscrobbler doesn't recognize artists, hence I can't love the tracks. It asks to edit the artists, which I do, but even after that, the artists don't get recognized. Those tracks get recognized by the official Lastfm app, the Musicbee software on Windows and the Last.fm website.
Ex. of one of those tracks = https://open.spotify.com/track/4lp3FDtmCE1F2bc6WQ6JUP?si=32b1109270d3480c
In this screenshot, the Last.fm app does recognize it, but Pscrobbler doesn't
![Screenshot_20210419-125451_Lastfm](https://user-images.githubusercontent.com/55885756/115226494-974e3b00-a10f-11eb-9a1b-c6687865a97a.jpg)

**Comment by kawaiiDango** [comment]
Tags like that usually will not get scrobbled by pano. Your Spotify link
scrobbles fine because Spotify cleans the tags.

**Comment by christubuntu** [comment]
> Tags like that usually will not get scrobbled by pano. Your Spotify link scrobbles fine because Spotify cleans the tags.

How do I edit the tags to be recognized. I'm using tagging apps like Automatag with no success.

**Comment by kawaiiDango** [comment]
You may try removing the second artist like Spotify does, or put a space after ; in the music file tag, so that pano can automatically remove it.

**Comment by christubuntu** [comment]
> You may try removing the second artist like Spotify does, or put a space after ; in the music file tag, so that pano can automatically remove it.

Adding a space did the trick. Thx.
