### ISSUE TITLE
Remove (Explicit) Option

### ISSUE THREAD

**Issue by El-Motu** [kawaiiDango/pScrobbler#129]
Not sure if this has been asked before, but searched and didn’t find one.

Is there a way to have an option that removes all (Explicit) tags by default? I know this is partially fixed by the ‘remember edits’ option, but for my music taste at least, this happens often and many times affects all tracks in an album so I’m continually adding edits.

Would there be a way to do this for all scrobbles as an option? In fact usually anything in brackets is something I like to remove to keep my scrobbles clean as Pandora loves to add useless stuff in (brackets) 😆

Thanks for all of the great work!

**Comment by kawaiiDango** [comment]
This is related to #17
If this was implemented, would you create a rule globally or only for Pandora?

**Comment by El-Motu** [comment]
> This is related to #17
> If this was implemented, would you create a rule globally or only for Pandora?

Hey KD, in my opinion it woudl make sense for it to be a global on/off toggle option in the settings, as Spotify does do it too, maybe not as often as Pandora, but it’s still there, a quick search for (explicit) on Spotify reveals this: 

![926B97D8-CC6E-48DC-B9A9-4E1F049FCC92](https://user-images.githubusercontent.com/74815525/116858481-574e8400-abf6-11eb-9fa4-a645bbf88f8b.png)

now the only issue is that it isn’t always standard, I.e sometimes you get (explicit) other times you get (explicit version), etc. So not sure how best to tackle this, maybe that’s what #17 is about?

Anyway, as always, keep up the great work, many of us around the world love tour stuff.

**Comment by Ryder9013** [comment]
> This is related to #17
> If this was implemented, would you create a rule globally or only for Pandora?

Definitely Global because Amazon Music does this too but like this "[Explicit]"

**Comment by kawaiiDango** [comment]
What would be some other common use cases for tag fixing? I might provide some presets since most people don't know regex.

**Comment by Ryder9013** [comment]
> What would be some other common use cases for tag fixing? I might provide some presets since most people don't know regex.

As far as I know albums have "(Remastered 2xxx)" or just "(Remastered)", (Album Version),(Explicit Version), (Explicit Album Version), [Explicit], [Clean] in case of Amazon Music, sometimes most weird ones are (Explicit version) [Explicit].

**Comment by kawaiiDango** [comment]
Implemented
