### ISSUE TITLE
Scrobbling with Apple Music doesn't work while casting

### ISSUE THREAD

**Issue by KiroKirilov** [kawaiiDango/pScrobbler#131]
Pretty much what the title says - when casting music to a chromecast, using apple music, the scribbling doesn't work. The "now playing" part works, but the track doesn't scrobble after 50%/3 minutes.

**Comment by kawaiiDango** [comment]
Casting will not work properly with some apps since the audio is not played
on the device. I'd still like to see a log. Send a bug report from the app.

**Comment by KiroKirilov** [comment]
Bug report sent, but what's weird is that it actually worked this time, but i have no idea what I did to fix it
