### ISSUE TITLE
[Feature Requests] Save Loved Tracks/Most played to an m3u playlist 

### ISSUE THREAD

**Issue by christubuntu** [kawaiiDango/pScrobbler#134]
The playlist could then be open by Music players. Music does this on Windows, but there's nothing on Android.
It does this by matching the lastfm data with files in your music library. I guess, by scanning the library on the phone, this app can generate a playlist matching the tracks on the lastfm servers. These are just assumptions, idk if it's possible m

**Comment by kawaiiDango** [comment]
That's not how m3u works. You need to know the file paths.

**Comment by christubuntu** [comment]
> That's not how m3u works. You need to know the file paths.

OK. But is it technically possible to acquire the file paths if this app is allowed to access the music folder?

**Comment by kawaiiDango** [comment]
No. The app has no idea whether something is played from a file. There has to be a one to one mapping from the lastfm entry to the music file. Also lastfm names can be different due to their autocorrect.
