### ISSUE TITLE
Scrobble YTB / YTB Music works when I pause only

### ISSUE THREAD

**Issue by Dyrium** [kawaiiDango/pScrobbler#137]
Hi KawaiiDango,

First of all, I would like to thank you for the development of the application which is really perfect, being able to modify the recent scrobble is really convenient.

But I have a bug since the last versions, I must have to "pause" the YouTube or YouTube Music video for the scrobble to start.

Without pausing, PanoScrobble doesn't launch and doesn't work.

I checked my phone settings (MIUI 12.0.2, Android 10), the battery saver is disabled, the application can start automatically and has access to notifications.
For the application settings (2.12 - 07.May.21), YouTube and YouTube Music are checked and I am still connected to LastFM.

I also uninstalled and reinstalled PanoScrobble but it doesn't change anything.

I should point out that this has been happening for the last 2/3 versions, it never happened before.

Thanks in advance for your help !

**Comment by kawaiiDango** [comment]
This is a YouTube bug.

**Comment by Dyrium** [comment]
Just with my YouTube apk or a bug with lastest version of YTB/YTB Music and I just need to wait a new version of YTB/YTB Music ?

**Comment by kawaiiDango** [comment]
The latest version of YouTube affects most scrobblers. Someone confirmed that it works fine on 16.15.x

**Comment by Dyrium** [comment]
Oh okay I think I will downgrade YTB then, thanks for this info and many thanks again for PanoScrobbler man !

**Comment by kawaiiDango** [comment]
I implemented a hack to treat the stoped state as the playing state for youtube and youtube music. This scrobbles the current versions, but this also means that stopped music will get scrobbled.

**Comment by Dyrium** [comment]
Thanks for this update, this hack you have implemented is to be activated in the options? Because I don't see it

However thanks to the update it works perfectly with the version 16.03.x that I use now, with the old update I had this bug also on the old versions of YouTube even with the 16.15.x I don't know why

**Comment by kawaiiDango** [comment]
Users don't have to do anything for that.

**Comment by kawaiiDango** [comment]
Does the latest YouTube scrobble?

**Comment by Dyrium** [comment]
Yeah, sorry for my late reply but it's work perfectly now thanks you !!

I'm using the lastest version of YouTube and PanoScrobble.

By the way, there is a way to force a modification ? Sometimes, I want to modify a wrong scrobble but I have error "Unrecognised artist"
