### ISSUE TITLE
"qps limit exceeded upgrade your account" 

### ISSUE THREAD

**Issue by angge1** [kawaiiDango/pScrobbler#138]
Hi KawaiiDango,

I just want to ask what's that statement mean because it's keeps on popping when I'm trying to scrobble from mic.

I also tried adding acrcloud key but when everytime I press verify, 🚫 appears.

Thank you

**Comment by kawaiiDango** [comment]
Yeah I'm planning to remove this feature in the next update. Do you actually need it when there is autoshazam scrobbling?

**Comment by angge1** [comment]
It's a good feature tho. It's the reason I choose the app.  I hope you change your mind 😉 jk
Anyway, thank you for responding.

**Comment by kawaiiDango** [comment]
What advantages do you think this feature has over autoshazam scrobbling?
