### ISSUE TITLE
[Feature request] F-Droid release?

### ISSUE THREAD

**Issue by TheWaschtlPlays** [kawaiiDango/pScrobbler#139]
I've recently been trIng to degoogle my phone and tech life, so therefore i've switched to F-Droid alternatives for many of my apps. This app is one of the remaining few (very) niche things. PanoSrobbler has become such an amazing open source app that i think an official repository on F-Droid would make this just perfect. Btw, this is now also my replacement for GoogleNow Music search.

**Comment by kawaiiDango** [comment]
This app is no longer foss as it uses the Google Play billing and acrcloud libraries which are closed source. However the Dropbox link to the latest apk is in the readme.
