### ISSUE TITLE
Pandora offline scrobbling

### ISSUE THREAD

**Issue by cchristian** [kawaiiDango/pScrobbler#14]
When I enable offline mode in Pandora they prepend "Offl- " to the artist name.  
Please try stripping that and trying again when you encounter an unknown artist.

**Comment by cchristian** [comment]
"Ofln - "

This is how it shows in Android Auto

![screenshot_20181115-191011](https://user-images.githubusercontent.com/3342922/48714031-c0d1a800-ebdf-11e8-98f9-aabc2cfe8011.png)

**Comment by kawaiiDango** [comment]
implemmented
