### ISSUE TITLE
Incorrect TuneIn Radio scrobbling (regex fix?)

### ISSUE THREAD

**Issue by Troetelbiertje** [kawaiiDango/pScrobbler#142]
On the TuneIn player a lot of radiostations show the station's name as the artist. And the artist and songtitle are both shown in the title field as 'Artist - Songtitle'. Which messes up the scrobbles.

I listen to the Kink station a lot, so all my scrobbles are now by the artist 'Kink'. It's too much work to correct each scrobble individually. Would it be possible to add a feature that allows custom rules to recognize and correct stuff like this automatically? Maybe regex could do the trick?

![Pano](https://user-images.githubusercontent.com/8169531/122728020-fc412100-d277-11eb-8a69-662cee7e9472.jpeg)

**Comment by kawaiiDango** [comment]
I'm not sure how regex would work through multiple fields

**Comment by kawaiiDango** [comment]
Should work now

**Comment by Troetelbiertje** [comment]
It does! Thanks a lot 🙌

**Comment by Troetelbiertje** [comment]
When listening through the official KINK radio app instead of using TuneIn, Pano still parses the artist and title incorrectly. Exactly the same happens like before you fixed it with TuneIn. Could you apply the same fix for the [Kink app](https://play.google.com/store/apps/details?id=app.kink.nl.kink)? Or is this something I could do myself?

![Screenshot_2021-12-11-16-05-43-68](https://user-images.githubusercontent.com/8169531/145687475-4bd9c442-46fa-4fd2-b95b-48d942403aa7.jpg)
![Screenshot_2021-12-11-16-10-30-45](https://user-images.githubusercontent.com/8169531/145687477-ced4b099-c80e-4c9c-982b-c184b56c78f2.jpg)

**Comment by xemles** [comment]
This issue seems to be a thing again. I didn't have it until recently
