### ISSUE TITLE
[Feature Request] Blacklist/Ignore scrobbles

### ISSUE THREAD

**Issue by Troetelbiertje** [kawaiiDango/pScrobbler#143]
Some radiostations on TuneIn output their station's slogan in the title tags during fillers, jingles, news, commercial breaks etc.
Pano Scrobbler thinks it are actual songs and scrobbles them. I'd love to add these to a blacklist so they won't get scrobbled.

**Comment by kawaiiDango** [comment]
I will consider this.

**Comment by kawaiiDango** [comment]
Implemented
