### ISSUE TITLE
Bug: podcasts app isn't ignored as configured

### ISSUE THREAD

**Issue by a-rekkusu** [kawaiiDango/pScrobbler#144]
steps to reproduce:
- connect PanoScrobbler to last.fm
- configure PanoScrobbler to ignore AntennaPod (FOSS podcasts app)
- play podcast from AntennaPod

expected result:
- podcast is not scrobbled

actual result:
- podcast is being scrobbled to last.fm

details: 
- version 2.22 on Android 11

**Comment by kawaiiDango** [comment]
Does it happen after a reboot?

**Comment by a-rekkusu** [comment]
yes, I have observed this over some time now. there have definitely been reboots in between.

**Comment by kawaiiDango** [comment]
Is auto detect apps enabled?

**Comment by a-rekkusu** [comment]
yes, I can try to play around with that toggle and re-test when I find the time

**Comment by a-rekkusu** [comment]
It seems like the issue doesn't happen when that toggle is switched off. It isn't really expected behaviour though, is it? Can you reproduce on your end? @kawaiiDango

**Comment by kawaiiDango** [comment]
With that setting turned on, it should scrobble even from unchecked apps which aren't listed in the music players and video streaming apps sections, unless you had checked and unchecked them at some time. It should also display a notification asking you to confirm that app. Check if you haven't blocked that notification.

**Comment by a-rekkusu** [comment]
I have indeed disabled all notifications. This ticket can be closed then, thanks for your help.
