### ISSUE TITLE
Force Album Artist to scrobble as Artist

### ISSUE THREAD

**Issue by pmcdonough8133** [kawaiiDango/pScrobbler#145]
The last.fm scrobbling api can take both Album Artist and Artist info from a track and pano does indeed submit both but the site itself is pretty terrible at handling splits and the like. It would be super nice if pano had an option to just default to using the Artist Metadata field when submitting the Album Artist Metadata field on each scrobble instead of trying to save edits for every split/various artist compilation

**Comment by kawaiiDango** [comment]
Closing as I will not be implementing this
