### ISSUE TITLE
"Radio Nowy Świat" - Radio Name as an artist

### ISSUE THREAD

**Issue by dariusz-wozniak** [kawaiiDango/pScrobbler#146]
Hi,

Would it be possible to whitelist radio stations that uses the following format and parse artist/title from the title (separated by `-` character).

Current format:

%artist%: %radio_station%
%title%: %artist% - %title%

Example:

%artist%: Radio Nowy Świat
%title%: The White Stripes - Offend In Every Way

Should be (for all tracks from the Radio Nowy Świat): 

%artist%: The White Stripes 
%title%: Offend In Every Way

Link: https://www.last.fm/music/Radio+Nowy+%C5%9Awiat/_/The+White+Stripes+-+Offend+In+Every+Way

**Comment by kawaiiDango** [comment]
Yes, as of now this is implemented by hardcoding the names of apps that have artist and title in the title

**Comment by dariusz-wozniak** [comment]
All right. The app name is 'Nowy Świat'. Can you please add it?

**Comment by kawaiiDango** [comment]
This will be added in the next update

**Comment by dariusz-wozniak** [comment]
Great, thank you :)

**Comment by kawaiiDango** [comment]
Implemented
