### ISSUE TITLE
Artist/track not parsed from NTS Radio app

### ISSUE THREAD

**Issue by jonpsp** [kawaiiDango/pScrobbler#148]
(also submitted through the app as a bug report)
The app is not scrobbling from the NTS Radio app correctly - it is picking up the track title as the artist, and nothing for the track title. SLS does get the correct details. See attached screenshot. 
(NTS Radio is detected as Chrome by SLS)

![TempScreenshot_20210715-124955_Chrome](https://user-images.githubusercontent.com/20799382/125799430-bcfe351f-0171-495f-ae18-04aff60aefac.png)

**Comment by jonpsp** [comment]
Here's the log
[log.txt](https://github.com/kawaiiDango/pScrobbler/files/6823594/log.txt)

Note this line suggests the artist was available:-
`07-15 12:46:17.471  7785  7785 I scrobbler: onMetadataChanged Mobb Deep () [Channel 2] ~ Shook Ones, Pt. II, sameAsOld=false, duration=0 lastState=3, package=com.android.chrome cb=83346821 sl=174098462`

**Comment by kawaiiDango** [comment]
This should be fixed in the latest update, however I keep getting "NTS Radio" as the song title in all scrobblers

**Comment by jonpsp** [comment]
Thanks!

It seems to be working, at least on the two songs I tried it on.  I think
you have to subscribe (i.e. pay money) to get the live track listing, which
might explain why you're only seeing "NTS Radio".

Jon
