### ISSUE TITLE
Loved track info in the notification

### ISSUE THREAD

**Issue by vekvoid** [kawaiiDango/pScrobbler#15]
Would be nice to be able to see in the notification if a track has been loved before, while scrobbling. Now, if we are listening a previous loved track, we cannot know, from de notification, if it is loved or not.

Maybe, the user track data could be fetched before showing the notification, so the heart be colored or not depending of the Loved status.

I guess the current behavior is really good to save mobile data, but it could be an option in the configuration section to enable this feature.

**Comment by kawaiiDango** [comment]
implemented. will also show the scrobble count in the notification, from the same api call
