### ISSUE TITLE
Regex across multiple fields

### ISSUE THREAD

**Issue by djryan** [kawaiiDango/pScrobbler#152]
Loving the pattern edits!

In Podcast Addict, podcasts with chapters appear as:

$TITLE - Chapter text
$ARTIST - Podcast Name
$TRACK - $Episode-Title ($Artist Name)

I've got a regex to pull out Episode Name as $1 and Artist Name as $2, but can only make the change in a single field.  Is it possible to read one field and edit another?

**Comment by pedrojvaz** [comment]
I'm a Podcast Addict user also and the incorrect mapping is annoying. I can't seem to figure out the pattern edits though. How do replace $Artist with Artist name?

**Comment by Goonik** [comment]
The same issue with RadioTunes app (former Sky.fm)
Metadata parsed incorrectly as follows:
$TRACK - always set to radio station name, Smooth Jazz or something else
$ARTIST - $(Artist name) - $(Track title)
$ALBUM - $(Track title)

$ARTIST field could be corrected with regex, but others are not. We need to be able to write regex capture groups into another fields.

**Comment by kawaiiDango** [comment]
I'm thinking of adding an extract mode. The user will be presented with 4 edit boxes, for the existing track, album, artist and album artist fields. They will need to use capture groups named exactly as track, album, artist or albumArtist to extract those fields from other fields. The user will also be able to limit a pattern edit to certain apps.

For the radiotunes example above, the user would need:
An extract rule:

TRACK - (blank)
ALBUM - (blank)
ARTIST - `(?<artist>.+) - (?<track>.+)`
ALBUM ARTIST - (blank)
Limit to: Radiotunes
Continue matching, if found: true

And another normal regex edit:

Pattern: `.+`
Fields: album
Replacement: (blank)
Limit to: Radiotunes

**Comment by forenta** [comment]
Has this feature been implemented? Maybe I'm missing it, I'm confused about the closure.

**Comment by kawaiiDango** [comment]
The extract mode has been implemented, yes.
