### ISSUE TITLE
Radio 357 is not being scrobbled

### ISSUE THREAD

**Issue by dariusz-wozniak** [kawaiiDango/pScrobbler#154]
Hi,

Scrobbling from "Radio357" Android app doesn't work. For most of the time, the app shows info about artist/track.

App link: https://play.google.com/store/apps/details?id=pl.Radio357

![IMG_20210730_113441](https://user-images.githubusercontent.com/5969160/127634084-f6c8fbf7-856b-4ae5-83a1-b65c3799e5db.jpg)

Can you please add support for the app?

**Comment by kawaiiDango** [comment]
Not possible

**Comment by dariusz-wozniak** [comment]
Just a FYI for those who want to scrobble from Radio 357 - you can use [VRadio](https://www.akouradio.com/) and add it to the Pano Scrobbler.
