### ISSUE TITLE
(Feat.) Pattern edit in artist field

### ISSUE THREAD

**Issue by Ryder9013** [kawaiiDango/pScrobbler#156]
First of all thanks a lot for addition of pattern edits using regex. I tried learning how to add my own pattern but am unable to do.
One suggestion I would really like in pattern edit is that some apps like Apple Music, Amazon Music have for example "Nas [feat. other artists]" in artist fields. This leads to multiple artists getting scrobbled instead of just the main one.
This would be great!
Thanks once again.

**Comment by kawaiiDango** [comment]
You could write  feat\..* which would remove feat and everything after that. Make sure you put a space before feat.

**Comment by kawaiiDango** [comment]
You can write  \\(?feat\\..* to include the bracket
