### ISSUE TITLE
Pattern edits removing more than the regex pattern is intended to

### ISSUE THREAD

**Issue by Ryder9013** [kawaiiDango/pScrobbler#159]
Right now Explicit and maybe other pattern edits too remove everything from the song field alongwith the regex pattern. Like Explicit removes (feat. Artist) alongwith (Explicit) from the song name. It would be great if you could separate (feat.) and explicit removal in the field as separate pattern edits.

**Comment by kawaiiDango** [comment]
You can edit the regex to remove only what you want
