### ISSUE TITLE
Not scrobbling looped songs

### ISSUE THREAD

**Issue by Botanistt** [kawaiiDango/pScrobbler#16]
There is a problem if you listen to the same song on repeat.
By doing so I'm loosing big amount of scrobbles, but it does scrobble some of them though.

**Comment by kawaiiDango** [comment]
Depends on the player. Which player are you using?

**Comment by Botanistt** [comment]
I am using Apple Music.

**Comment by kawaiiDango** [comment]
Can't test that without a subscription

**Comment by Botanistt** [comment]
It actually offers 3 month free trial.

**Comment by kawaiiDango** [comment]
Thanks, will test

**Comment by Botanistt** [comment]
no problem! Thanks.

**Comment by Botanistt** [comment]
Hey. I noticed that sometimes after the song is being played again it still marks it at scrobbled instead of starting to scrobble again. If I start song manually then it resets and seems to be working fine.

I hope this helps.

**Comment by jarko88** [comment]
Phonograph have the same problem with multi loop song

**Comment by kawaiiDango** [comment]
should be fixed now
