### ISSUE TITLE
Album Artist pattern edit (for feat.) not functioning

### ISSUE THREAD

**Issue by Ryder9013** [kawaiiDango/pScrobbler#165]
![Screenshot_20210824-192843_Pano Scrobbler](https://user-images.githubusercontent.com/75566707/130630126-cbc7fb79-40e9-448d-a19a-d5bfec351025.jpg)
I have applied a regex pattern to remove (feat. artist) from Album Artist field (because in Amazon Music it pulls the same tag for artist, album artist). Now it corrects the artist properly but it still says artist not recognised. 
![Screenshot_20210824-191813_Pano Scrobbler](https://user-images.githubusercontent.com/75566707/130628674-e28e9840-cb98-4928-9faf-1f880f29e667.jpg)

**Comment by kawaiiDango** [comment]
Could not reproduce this. But this could be the cache, force stop and restart the app to clear that.

**Comment by Ryder9013** [comment]
It says "artist not recognised" even when the artist gets corrected through regex. Listen to this song
Can It Be All So Simple (Remix) [Explicit] by Raekwon feat. Ghostface Killah on Amazon Music
https://music.amazon.in/albums/B00136JS8U?trackAsin=B00136LIXI&ref=dm_sh_o5LaBdammcTRXn0mKTc9vsp88 
![Uploading Screenshot_20210828-235838_Pano Scrobbler.jpg…]()

**Comment by Ryder9013** [comment]
It says "artist not recognised" even when the artist gets corrected through regex. Listen to this song
Can It Be All So Simple (Remix) [Explicit] by Raekwon feat. Ghostface Killah on Amazon Music
https://music.amazon.in/albums/B00136JS8U?trackAsin=B00136LIXI&ref=dm_sh_o5LaBdammcTRXn0mKTc9vsp88
![Screenshot_20210828-235838_Pano Scrobbler](https://user-images.githubusercontent.com/75566707/131227470-ff1cadd4-88a6-454d-a1e8-0261fb23f323.jpg)
The album artist gets corrected to "Raekwon" but still says not recognised like the notification screenshot in my issue post at the top.

**Comment by kawaiiDango** [comment]
I don't have access to Amazon music but it looks like you didn't include a space in the regex, so the artist gets corrected to "Raekwon ", which doesn't exist.

**Comment by Ryder9013** [comment]
Where should I include a space?

**Comment by Ryder9013** [comment]
Fixed it! Thanks for the help. Just put a space first then regex!
