### ISSUE TITLE
[Feature Request] Regex-based tag fixing

### ISSUE THREAD

**Issue by Reyth3** [kawaiiDango/pScrobbler#17]
We all know how Spotify handles their `(Remastered)` releases. THere's also other apps that add random strings of text to the song/album name (for example: https://www.last.fm/music/%E6%A1%91%E5%8E%9F%E7%94%B1%E6%B0%97%2F%E9%95%B7%E7%B8%84%E3%81%BE%E3%82%8A%E3%81%82%2F%E9%AB%98%E7%94%B0%E6%86%82%E5%B8%8C%2F%E9%AB%98%E6%A9%8B%E6%9C%AA%E5%A5%88%E7%BE%8E/_/%E3%82%A4%E3%82%B7%E3%83%A5%E3%82%AB%E3%83%B3%E3%83%BB%E3%82%B3%E3%83%9F%E3%83%A5%E3%83%8B%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3+(TV%E5%8A%A8%E7%94%BB%E3%80%8A%E5%B0%8F%E6%9E%97%E5%AE%B6%E7%9A%84%E9%BE%99%E5%A5%B3%E4%BB%86%E3%80%8B%E7%89%87%E5%B0%BE%E6%9B%B2+%2F+TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E5%B0%8F%E6%9E%97%E3%81%95%E3%82%93%E3%81%A1%E3%81%AE%E3%83%A1%E3%82%A4%E3%83%89%E3%83%A9%E3%82%B4%E3%83%B3%E3%80%8DED%E3%83%86%E3%83%BC%E3%83%9E)

It would be extremely useful if we could define regex-based rules and filters for the scrobbler to automatically get rid of these unneeded parts of the metadata. 

Thank you!

**Comment by kawaiiDango** [comment]
Implemented
