### ISSUE TITLE
Can't authorize last.fm on cellular data and abnormal icon

### ISSUE THREAD

**Issue by lostb053** [kawaiiDango/pScrobbler#174]
Am on **Android 6.0.1** / **Oppo A57** / **ColorOS V3 0.0i**,
Normally i wouldn't complain about this as I'm using old phone, but pano supports old OS, and seems to be working fine on my **Android 5** / **ColorOS 2.0**

The below is abnormal icon (looks weird, dont wanna see it, but ok, can probably just hide it somewhere in folders)
![Screenshot_2021-09-24-09-38-37-00](https://user-images.githubusercontent.com/72547660/134616945-a82107a9-e594-4c34-a29c-ea911453bf0c.png)

But then came next issue. Now that's what i get when i go for authorising last.fm
![Screenshot_2021-09-24-09-38-44-72](https://user-images.githubusercontent.com/72547660/134617529-577cac5d-0edc-4ea2-841d-ad86b3d0a6ca.png)

Well, this app is really good except for the fact that i cant use it, as i had to switch my phone (well again using my dad's old phone lol)
Hope it gets fixed soon

**Comment by lostb053** [comment]
Update: can't authorize with my own net, but works with wifi, please check if it's some issue in the app, or maybe error with my net
Still would be grateful if you can fix abnormal icon lol

**Comment by kawaiiDango** [comment]
None of these look like an issue with the app as I cannot reproduce them.
Check if your isp is blocking lastfm and you might need a vpn.

**Comment by lostb053** [comment]
> None of these look like an issue with the app as I cannot reproduce them. Check if your isp is blocking lastfm and you might need a vpn.

Well probably i should blame isp (Jio), will try with vpn, but icon??
Hope u can fix it

**Comment by kawaiiDango** [comment]
There's nothing to fix

**Comment by lostb053** [comment]
> There's nothing to fix

Ahh
Ok
