### ISSUE TITLE
I need help with pattern edits.

### ISSUE THREAD

**Issue by NomaanMalick** [kawaiiDango/pScrobbler#176]
I use Apple Music and singles and EPs on there have a " - Single", " - EP", and " - E.P." added to information that goes in the album section of the scrobble. I want to know how I can set up my pattern edits to automatically remove this information from my scrobbles. Also, I would appreciate help with removing information like "(Deluxe)", "(Deluxe Edition)", etc., from my scrobbles.

**Comment by MaksRawski** [comment]
Hi, so for removing the single and EP information you could use:
` - (single|E\.?P\.?)`
and as for the deluxe editions:
`\(Deluxe .*\)`
You'll have to put them as a Regex pattern and leave the Regex replacement empty. 

Unfortunately I'm not aware of any great introduction into regular expressions, however I really enjoy using [regex101](https://regex101.com) for testing or even just playing around with them. So you may want to check that out if you would like to write something similar yourself in the future.

**Comment by NomaanMalick** [comment]
Thank you very much!

**Comment by NomaanMalick** [comment]
Thank you very much for all the help!

**Comment by NomaanMalick** [comment]
Thank you very much for all the help!
