### ISSUE TITLE
A couple of feature requests

### ISSUE THREAD

**Issue by awsms** [kawaiiDango/pScrobbler#178]
- Copy artist/trackname/songname to clipboard by pressing them for a second
- Add a button to search on music players by trackname / album name as well
- Remove the dash -   between artist and trackname when doing a search, this messes up a lot of audio players for some reason (including spotify)

(on this menu: ![](https://i.imgur.com/avOaorQ.png))

**Comment by kawaiiDango** [comment]
How does the dash mess up?
