### ISSUE TITLE
One pattern edit, one suggestion

### ISSUE THREAD

**Issue by Ryder9013** [kawaiiDango/pScrobbler#179]
~Recently I've experiencing that when the phone is locked the app misses scrobbling songs sometimes. Like say I heard a song when phone was unlocked and it was scrobbling. After I lock it doesn't scrobble next songs. It gets stuck at "Song Name" scrobbles in notification. Then as soon as I unlock it starts scrobbling currently playing song but before that songs are missing.~ (Seems to be fixed for now after restarting device)

Pattern Edit - some artists are named as for example - Freddie Gibbs & Madlib. So I only want to scrobble "Freddie Gibbs" in artist field. Of possible u can tell me the regex pattern now or add in future update.

One suggestion - It would be nice to have a telegram group or discord server or something like that for small questions and general discussion with other users.

**Comment by NomaanMalick** [comment]
> Pattern Edit - some artists are named as for example - Freddie Gibbs & Madlib. So I only want to scrobble "Freddie Gibbs" in artist field. Of possible u can tell me the regex pattern now or add in future update.

Isn't that bad practice? Since both artists contributed towards the work, the scrobbles should count towards the combined artist tag, shouldn't they? I am curious to hear your reasoning.

**Comment by Ryder9013** [comment]
> > Pattern Edit - some artists are named as for example - Freddie Gibbs & Madlib. So I only want to scrobble "Freddie Gibbs" in artist field. Of possible u can tell me the regex pattern now or add in future update.
> 
> Isn't that bad practice? Since both artists contributed towards the work, the scrobbles should count towards the combined artist tag, shouldn't they? I am curious to hear your reasoning.

I understand what you are saying and I agree. The thing is that when I scrobble it as both it would create a new artist instead of the scrobbles going to the artist I already have in my library with lots of scrobbles.

**Comment by NomaanMalick** [comment]
Ideally, Last.fm would have a mechanism in place to identify the contributing artists and equally have the scrobble count towards each artist tag but as things stand, it just creates a new artist tag with the names combined. I don't mind it and in fact, I switched from Spotify to Apple Music for this reason because the Last.fm Spotify connector would just scrobble the track in favour of the first artist in credited in the artist field.

**Comment by flickur** [comment]
>I understand what you are saying and I agree. The thing is that when I scrobble it as both it would create a new artist instead of the scrobbles going to the artist I already have in my library with lots of scrobbles.

If the artist is actually named as 'Artist 1 & Artist 2' with an '&' and not just 'Artist 1, Artist 2', it's intended by the artists and should be used as a collaboration tag.

**Comment by Ryder9013** [comment]
> > I understand what you are saying and I agree. The thing is that when I scrobble it as both it would create a new artist instead of the scrobbles going to the artist I already have in my library with lots of scrobbles.
> 
> If the artist is actually named as 'Artist 1 & Artist 2' with an '&' and not just 'Artist 1, Artist 2', it's intended by the artists and should be used as a collaboration tag.
> 
> As for how last.fm should handle these, it's just like said above but that will not happen. Last.fm doesn't even have the autocorrects working properly after 3 years of their new database. Keep in mind this feature worked perfectly already back in like 2009.

In my case not intended. On YouTube and Amazon Music if Artists are named as Artist 1, Artist 2 they get renamed with '&' in between.

**Comment by kawaiiDango** [comment]
https://github.com/kawaiiDango/pScrobbler/issues/177
