### ISSUE TITLE
My conjecture, may be there is a notification usage conflict with QuickLyric

### ISSUE THREAD

**Issue by qwertyuser1983** [kawaiiDango/pScrobbler#18]
I have each installed in my phone, Nokia 6.

When using Just Player, Quicklyric work normally. Pano did not scrobble anything.

When using Vanilla Player, Pano work normally. Quicklyric fail to load the next song. Quick stay in the previously played song.

Please help.

**Comment by kawaiiDango** [comment]
Both work fine here on lineageos on one plus x

**Comment by qwertyuser1983** [comment]
Apparently, after several trial,
Pano Scrobbler must be started after Quicklyrics. 

I guess problem solved, somehow. 
:+1:
