### ISSUE TITLE
Why don't the pattern edits always work?

### ISSUE THREAD

**Issue by NomaanMalick** [kawaiiDango/pScrobbler#180]
Previously, I asked for help regarding pattern edits and [this kind person helped me with setting up a few of my own](https://github.com/kawaiiDango/pScrobbler/issues/176#issuecomment-944985613). After initial success, I have found that occasionally, they fail to weed out suffixes like " - Single" and " - EP". I hope you can help me with resolving this error.

**Comment by kawaiiDango** [comment]
Can you provide a way to reproduce this?

**Comment by NomaanMalick** [comment]
Thank you very much for your response! Here is what I am talking about:
Right now, the tracks I can remember giving me this problem while scrobbling are the ones by Metronomy & spill tab, Melin Melyn, and Sabi Lulu (as you can see from their place in my edits). 
![Screenshot_20211118_220210_com arn scrobble](https://user-images.githubusercontent.com/46681247/142459551-cf06862c-9a64-4c04-86a0-f68cdca44f99.jpg)

After deleting them from my edits and scrobbling them again, Pano Scrobbler fails again to weed out the suffix " - Single" from the Melin Melyn and Sabi Lulu tracks, and in Metronomy & spill tab's case, it strangely fails to register the name of the album in the album field.
![Screenshot_20211118_220630_com arn scrobble](https://user-images.githubusercontent.com/46681247/142459686-5e99979f-514b-4a9c-8725-84965bda4e08.jpg)

![Screenshot_20211118_220525_com arn scrobble](https://user-images.githubusercontent.com/46681247/142459787-38c984f8-da48-409f-9fb5-485a212e4f1c.jpg)

![Screenshot_20211118_220359_com arn scrobble](https://user-images.githubusercontent.com/46681247/142459859-c9e347e8-6954-49cd-b108-74aed3918980.jpg)

![Screenshot_20211118_220630_com arn scrobble](https://user-images.githubusercontent.com/46681247/142459929-080dff9c-8a7e-40e1-8365-6f23f3df1598.jpg)

**Comment by kawaiiDango** [comment]
Which player are you scrobbling from? Is the original album field actually blank?

**Comment by NomaanMalick** [comment]
Apple Music. 
https://user-images.githubusercontent.com/46681247/142607000-f5eb27d9-9a20-4546-bd2c-783afe857db7.mp4

**Comment by kawaiiDango** [comment]
Can you send logs with the app's bug report while scrobbling those songs?
Just want to confirm if Apple music is sending blank albums for all of
them. In that case, Pano would fetch an album from lastfm if found and fill
it, like webscrobbler does and those albums happen to have "- Single'' in
them.

**Comment by NomaanMalick** [comment]
Hey! Thank you again, for being kind enough to listen to issues I am having with the app. It means a lot. 

So, I played the songs again through Apple Music and this time the app scrobbled them without the " - Single" suffix. I checked my edits to ensure that I didn't have the edits saved for these tracks. However, the Metronomy & spill tab track scrobbles with "Posse, Volume 1 -EP" in the album field now without removing the EP suffix. Initially, I thought the pattern edit for weeding out the EP suffix wasn't working again until I noticed that the EP in the " -EP" suffix, in this case, doesn't have a space between the hyphen and the letter E of EP. This leads me to the question that what should I write in the pattern edit menu to account for incidents like these?

Thanks in advance!

**Comment by kawaiiDango** [comment]
I guess Apple music sometimes passes the album data and sometimes a blank. Can't confirm anything without the logs though. For regex issues, you can test them at regex101.com The app also has a regex test button

**Comment by NomaanMalick** [comment]
I emailed you the log file about issue regarding scrobbling with an empty album field.

**Comment by kawaiiDango** [comment]
The blank album pattern edit issue will be fixed in the next update.

**Comment by NomaanMalick** [comment]
Thank you very much!
