### ISSUE TITLE
"Now playing" not scrobbling with German language setting.

### ISSUE THREAD

**Issue by richteas75** [kawaiiDango/pScrobbler#181]
I just checked my last.fm scrobbling history and noticed that for more than a year (at least from October 2020), Pixel's "now playing" hasn't been scrobbled to my last.fm account: none of the tracks listed in my "now playing" history on my smartphone appear on last.fm. 
I then tested live with a random song, which was correctly picked up by the "now playing" feature, but not scrobbled to last.fm.

I'm using the German (Germany) language setting (android system-wide), so on a whim, I tested again with English (United States) as system wide language setting - and after that language change, "now playing" was correctly detected by pano scrobbler.

In pano scrobbler configure, the options "scrobble Pixel's now playing" and "submit now playing" are both activated. Scrobbling delays are set to 30 percent/ 30 seconds. It seems that UI language setting in pano scrobbler does not have an effect.

This is on a Google Pixel 3a which has been kept updated with the official android version for this device (currently android 12), and panoscrobbler installed and updated from the Google Play Store.
All other scrobbles (from youtube music, spotify or youtube as well as "scrobble from mic") work correctly.

I'm open to help with additional tests.

**Comment by kawaiiDango** [comment]
Can you post a screenshot of the German text in the now playing
notification? I guess the quotation marks have changed?

**Comment by richteas75** [comment]
![Screenshot_20211123-084318_Now Playing](https://user-images.githubusercontent.com/76160540/142986976-2d7ebfc7-b3a9-4483-a4e1-e097142900fa.png)

**Comment by kawaiiDango** [comment]
Yeah the German text has changed. The strings will be updated in the next release.

**Comment by kawaiiDango** [comment]
Should be fixed now

**Comment by richteas75** [comment]
> Should be fixed now

Yes, works like a charm. Thank you!
