### ISSUE TITLE
Suggestion: donations through Google Play credit

### ISSUE THREAD

**Issue by bt-abba** [kawaiiDango/pScrobbler#183]
Hello, I have a pretty hefty amount of Google Play credit from completing Google Rewards surveys. This credit is generally useless to me besides supporting devs/projects I like. 

The in-app donation/upgrade option in PanoScrobbler currently only accepts CC/PayPal payment. I would love to be able to donate these credits to Pano if possible, so please consider making this an option.

- Ben

**Comment by kawaiiDango** [comment]
This is something that only Google has control over. I have bought several in apps with Google Play balance that I got from Google Play recharge codes. Check with Google if your country is supported or if you are missing something.
