### ISSUE TITLE
Missing scrobbles when phone is locked

### ISSUE THREAD

**Issue by Ryder9013** [kawaiiDango/pScrobbler#184]
When I lock my phone the app has been missing scrobbles. It keeps scrobbling if screen is on but not when locked.

**Comment by NightLancer** [comment]
@Ryder9013 maybe your power-saving setting disables the app after some time when blocked(usually 5mins or so)? I set zero energy saving for this scrobbler and for my online-player and it always works. It's not general "energy saving" mode, you need to find app in your app/settings list and change it there.

**Comment by Ryder9013** [comment]
Battery saver was turning on automatically which seemed to be the problem. Seems fine now. Thanks.
