### ISSUE TITLE
Is it possible to include an option to toggle the app to always force scrobble when it doesn't recognise the artist tag? 

### ISSUE THREAD

**Issue by NomaanMalick** [kawaiiDango/pScrobbler#186]
I recently noticed that some of the music I had played hadn't been scrobbled by the app because it couldn't recognise the artist tag. So, I was wondering if it was possible to include an option to toggle the app to always force scrobble when it doesn't recognise the artist tag? ![Screenshot_20211211_084940_com arn scrobble](https://user-images.githubusercontent.com/46681247/145689287-1eee875f-3161-4c7e-9b1d-56df87dab924.jpg)

**Comment by kawaiiDango** [comment]
Artist searching has now been disabled except for youtube and browsers
