### ISSUE TITLE
Scrobble not recorded or pushed to last.FM if track is rewinded or paused

### ISSUE THREAD

**Issue by quietmansoath** [kawaiiDango/pScrobbler#189]
![Screenshot_20211217-213509](https://user-images.githubusercontent.com/46270221/146626760-c9adf9b8-476f-4739-b0a0-9516ab6de3da.png)

As you can see, the scrobbler is only recording two scrobbles. The top listing was not recorded since I paused the song halfway through. The second one was not recorded because the song was rewinded before it fully ended (had about 5 seconds left to go).

I have tested this on a few music players on Android 11, so it's not player specific. I can't even imagine how many scrobbles I've "lost" because of this issue.

**Comment by kawaiiDango** [comment]
I couldn't reproduce this. The song has to be played for some time before
it gets scrobbled, if that's what you are talking about.

**Comment by quietmansoath** [comment]
Yes, the settings for me are 30% if the song, or 1:00 (one minute) or play time.
I restarted my phone and still have this issue. I can even watch it happening within the notification. The song will say it's scrobbled, but if I rewind it before it finishes playing, the scrobble counter will go down as if the scrobble didn't happen at all. But then if I click into the stats, it will show up like the above.

If you can't reproduce it, what should I do? Is there any additional information I can give that might help?

**Comment by kawaiiDango** [comment]
Send a bug report from the app shortly after reproducing this issue, so
that it gets captured in the logs.

**Comment by quietmansoath** [comment]
Thanks, actually you can close this. It seems like there is quite a bit of a lag but the song counter does eventually update to match. Not sure what causes it to finally update but if it works, I'm happy. Sorry!

**Comment by kawaiiDango** [comment]
Lastfm servers can sometimes lag. And then there was an outage yesterday.
