### ISSUE TITLE
Android TV 9

### ISSUE THREAD

**Issue by Harmonie666** [kawaiiDango/pScrobbler#190]
Trying to scrobble YouTube Music with Pano Scrobbler in ATV, but it doesn't work. Tried with stock YT too, signed out and in, gave permission to PanoScrobbler again. It just doesn't scrobble YouTube Music.

![PXL_20211226_010513967.jpg](https://user-images.githubusercontent.com/73917917/147407112-64c09b12-b622-4f47-b41a-524eb7b38bf9.jpg)![PXL_20211226_010547686.jpg](https://user-images.githubusercontent.com/73917917/147407114-a9d5d7b6-6528-4b3d-8a96-e433dd6a08af.jpg)

I have to add it worked with Deezer and ATV. But I quit Deezer, and want to scrobble YouTube Music on my TV. It also works with YouTube Music and PanoScrobbler in my Android phone. Only ATV doesn't work.

**Comment by kawaiiDango** [comment]
You need to enable YouTube and not YouTube music

**Comment by Harmonie666** [comment]
> You need to enable YouTube and not YouTube music

I've enabled only YouTube now, and played a few tracks to the end. Didn't scrobble.

And before you say I have to enable both YouTube and YouTube Music (which is basically within the same app) I did that previously and didn't scrobble either 😣

**Comment by Harmonie666** [comment]
@kawaiiDango Hello. I'm not sure if you've seen my replies?

**Comment by kawaiiDango** [comment]
I think you are talking about #150

**Comment by Harmonie666** [comment]
> I think you are talking about #150

No I don't see any similarities between these two issues. Autor of that post wants to scrobble using NewPipen(from his phone) while I want to scrobble using YTM on desktop.

**Comment by kawaiiDango** [comment]
https://github.com/kawaiiDango/pScrobbler/issues/150#issuecomment-882648487

**Comment by Harmonie666** [comment]
> https://github.com/kawaiiDango/pScrobbler/issues/150#issuecomment-882648487

No the issue is not differentiating between videos and music. The issue is PanoScrobbler on Android TV doesn't scrobble ANYTHING despite me having both YouTube and YouTube Music enabled in it's settings. It does not scrobble.

**Comment by Harmonie666** [comment]
See:

![PXL_20220109_162635735.jpg](https://user-images.githubusercontent.com/73917917/148691194-00ac6bf9-5e3c-4ae9-b1be-f8a49eb50603.jpg)

**Comment by Harmonie666** [comment]
> See:
> 
> ![PXL_20220109_162635735.jpg](https://user-images.githubusercontent.com/73917917/148691194-00ac6bf9-5e3c-4ae9-b1be-f8a49eb50603.jpg)

YTM section in YouTube Android TV app:

![PXL_20220109_162729458.jpg](https://user-images.githubusercontent.com/73917917/148691228-76876b56-7086-4a95-a5fe-15bd37e46fda.jpg)

**Comment by kawaiiDango** [comment]
Yeah why does it not scrobble? Because it doesn't know whether this is a music release or a normal video, so it doesnt know what the artist/track is and what to scrobble. This is what the linked issue explains.

**Comment by Harmonie666** [comment]
Well I finally get what you're trying to explain. Is there any possibility to fix this issue?
