### ISSUE TITLE
[Feature Request] Include option "This Year" in the "Charts" section.

### ISSUE THREAD

**Issue by NomaanMalick** [kawaiiDango/pScrobbler#191]
In the "Library" section available on a user's profile, we can view the scrobble history for any time period using this option: ![image](https://user-images.githubusercontent.com/46681247/147416063-583c6809-cb80-4767-9ee6-33fcd28e9631.png)

I find this option useful for viewing my scrobble history for the ongoing year or any given month. I was hoping that it would be convenient if this feature available on the website was packaged as "This Year" and "This Month" on the app. Or, instead of "This Year", the feature could be made available as "2021", "2020", "2019", going back to the year the user signed up for last.fm.

**Comment by kawaiiDango** [comment]
There's a calendar button in the app

**Comment by NomaanMalick** [comment]
@kawaiiDango Thank you for your response! I am aware that there is a calendar button in the app, but as far as I understand it can only be used for viewing the music scrobbled on any given day and not a given time period i.e., 10 days, 30 days, a month, or a year, etc.

**Comment by kawaiiDango** [comment]
It works as the "from" date with no limits on the "to" date.

**Comment by NomaanMalick** [comment]
@kawaiiDango I was hoping for a feature that would also provide the "from date" option. But if that's not possible, that's alright. We are thankful for your work regardless!

**Comment by kawaiiDango** [comment]
Oh I missed the title of the issue. This is not possible for charts for 3rd party apps.

**Comment by NomaanMalick** [comment]
@kawaiiDango Oh! That's too bad. Still, thank you for letting me know.

**Comment by kawaiiDango** [comment]
It looks like it is possible even though it isn't intended to be. The
weekly charts api accepts arbritary date ranges, not just weeks. The
feature will be implemented.

**Comment by NomaanMalick** [comment]
@kawaiiDango That's great to hear! Thank you very much!
