### ISSUE TITLE
"Last fm ignored this scrobble" 

### ISSUE THREAD

**Issue by Ryder9013** [kawaiiDango/pScrobbler#193]
This notification can no longer be clicked to edit the song info. In previous versions clicking on it opened the app and let the info be edited.

**Comment by kawaiiDango** [comment]
>  In previous versions clicking on it opened the app and let the info be edited.

No it didn't

**Comment by Ryder9013** [comment]
> > In previous versions clicking on it opened the app and let the info be edited.
> 
> It didn't

I remember clicking the notification at least let me edit the info for it to be accepted by last fm also there was a tick force scrobble. But I might be wrong.

**Comment by kawaiiDango** [comment]
It's a different notification. It's still there.
