### ISSUE TITLE
Srobbling does not work on some radio music apps

### ISSUE THREAD

**Issue by zilpe** [kawaiiDango/pScrobbler#194]
When playing the live radio on the BBC Sounds app, the scrobbler detects the song playing and is visible in the scrobbler app when the song is playing (as the BBC Sounds app changes the current track metadata in real time).

However, when the next song plays, the scrobbled song is not actually stored/sent to last.fm. It just disappears from Panoscrobbler and the next song appears which is playing on the radio. Scrobbling works just fine in more typical streaming apps such as YouTube Music.

Thanks for your work!

**Comment by kawaiiDango** [comment]
The song has to be played for some time to get scrobbled, 4 minutes by default. I think you are having issues with songs that are shorter than 4 minutes.

**Comment by zilpe** [comment]
That's exactly it. Thanks!
