### ISSUE TITLE
PanoScrobbler is displaying&saving different album cover art than what is shown in YTM.

### ISSUE THREAD

**Issue by Harmonie666** [kawaiiDango/pScrobbler#195]
I'm using YouTube Music and I noticed that often times PanoScrobbler shows and saves a different album art cover to LastFM. 

I would like for it to display the exact same cover art that is being shown to me in YouTube Music. 
Can this behavior be changed to match YTM cover art? 
Why doesn't PanoScrobbler get the cover art from YTM directly, and instead prefers to get it from another source? Example:

YTM cover art:

![Screenshot_20220110-011201614.png](https://user-images.githubusercontent.com/73917917/148706953-812342c6-af74-4d2e-8629-c37a1ee366f0.png)

What PanoScrobbler saves as Cover art:

![Screenshot_20220110-011152771 (1).png](https://user-images.githubusercontent.com/73917917/148706963-333198f9-30a4-4188-ab7d-0b41ca7633f3.png)

**Comment by kawaiiDango** [comment]
> Can this behavior be changed to match YTM cover art? 
No

**Comment by Harmonie666** [comment]
> 
> > Can this behavior be changed to match YTM cover art? 
> No
> 

Why is that? Would like to hear the technical explanation.

**Comment by kawaiiDango** [comment]
There's no technical reason. It's a choice for consistency in the images.

**Comment by Harmonie666** [comment]
> There's no technical reason. It's a choice for consistency in the images.

Well I would prefer to use the consistent cover art from YTM. It's weird to see different cover art from YTM in my LastFM account.
Different services often offer different cover art.
Where does PanoScrobbler even get the cover art from? Could this be made into user choice? For example a setting that says "use cover art of your music streaming service"

**Comment by kawaiiDango** [comment]
This is a lastfm client, so it gets its data from lastfm, obviously. I'd like to keep it that way. If you do want to add other sources, feel free to create your own fork of this repo.

**Comment by Harmonie666** [comment]
I don't have the experience to do it. That's unfortunate, I would've liked being given to possiblity to choose for myself.
Anyway, thanks for developing the app :)
