### ISSUE TITLE
pScrobbler scrobbling latest song at seemingly random times

### ISSUE THREAD

**Issue by Fyde1** [kawaiiDango/pScrobbler#20]
pScrobbler often floods my last.fm profile with the same song that I haven't actually listened to, here's an example.

<img width="837" alt="screen shot 2019-01-15 11 01 25 am" src="https://user-images.githubusercontent.com/39483354/51173168-1f03ca00-18b5-11e9-8d6c-e05b088ec4a6.png">

That's just the song I paused on Spotify last time I used it, I have never even listened to it once. 
I'm not 100% sure what causes this, but it happens sometimes when I connect my bluetooth headphones (the first and second instance in that screenshot) and sometimes when my phone connects to a wifi network.

Let me know if you need any more information.

**Comment by kawaiiDango** [comment]
Spotify has other issues too with the notification listener method of scrobbling. I recommend turning off Spotify and enabling server side scrobbling from lastfm

**Comment by Fyde1** [comment]
Thanks, I did that.
