### ISSUE TITLE
App scrobbles artists incorrectly

### ISSUE THREAD

**Issue by klmkyo** [kawaiiDango/pScrobbler#201]
When using Pano Scrobbler with Tidal, the app includes featured artist in the scrobble, which results in the scrobbles pointing to the wrong track. I tried making regex to fix the issue (which would work by selecting the sequence before the first comma), but this would require to create some sort of exception list for artists such as `Tyler, the Creator`, which I honestly don't really know how to do. Perhaps there could be a feature in the app that would fix such issue automatically, using a list of exceptions.

![chrome_B7e9Rvllmq](https://user-images.githubusercontent.com/47790222/150705058-6eeca4b6-d7fb-4352-91cf-fa53acee9b6d.png)
Pointing to this https://www.last.fm/music/Tyler,+The+Creator,+Jaden/_/Pothole+(feat.+Jaden+Smith)

![chrome_ovJx3Qjh86](https://user-images.githubusercontent.com/47790222/150705066-991d8a23-8b86-4d7d-afa2-0be745acad8e.png)
Pointing to this https://www.last.fm/music/Little+Simz,+Cleo+Sol/_/Woman

**Comment by Drh44** [comment]
hey klmkyo, I have made a set of regexes that work with this. There are three of them and have to be in a certain order. I can send you screenshots of how to set them up but github took away the pm feature. If you want the regex, shoot me a email at Hesmeister20@gmail.com

**Comment by Drh44** [comment]
basically you need a priority regex that checks for tyler, the creator featuring a artist.
second there will be a regex for just Tyler, the Creator
lastly there is a regex to remove the featured artists from the artists section. 
I'm not 100% sure it works in all cases and it is only for Tyler, the Creator, however if you run into another artist with a comma you can just copy the regex and replace the necessary parts

**Comment by klmkyo** [comment]
Thanks for reaching out, I'd love to take a look at those regexes! Could you maybe provide them here? Could be useful to the people who also currently struggle with this problem.

**Comment by Drh44** [comment]
I have them being sent as screenshots. The order they are in has to be
exact as the first two kinda act as preventers for the 3rd

**Comment by Drh44** [comment]
For any other artist with a comma in their name, they can be checked just
like the Tyler one, he was just the only artist I could think of currently
