### ISSUE TITLE
Won't scrobble with regex edit?

### ISSUE THREAD

**Issue by zhutra** [kawaiiDango/pScrobbler#202]
Hello,
I am using PanoScrobbler for scrobbling internet radio (a shoutcast stream).
However, all players I have tried set the radio station as the album name.

So inside Pano I made a regex to remove the station name, leaving the album field empty.
With this regex, Pano displays the correct metadata for the song. 
However, whenever the track finishes, it doesn't scrobble anything to my profile.

If I manually edit every single song and remove the album field, leaving it empty, it does scrobble though.
But I don't want to have to this for every single track, especially considering it is an online radio.

Is there anything I can do to fix this issue?

**Comment by kawaiiDango** [comment]
Can you mention which players you have tried? I might try to find a pattern. 

Your workaround scrobbles fine for me in Poweramp (which does put the station name in the album). Your issue might be https://github.com/kawaiiDango/pScrobbler/issues/194#issuecomment-1008325829

**Comment by zhutra** [comment]
> Can you mention which players you have tried? I might try to find a pattern.
> 
> Your workaround scrobbles fine for me in Poweramp (which does put the station name in the album). Your issue might be [#194 (comment)](https://github.com/kawaiiDango/pScrobbler/issues/194#issuecomment-1008325829)

Hi there @kawaiiDango   
I was using XiiaLive Pro. I tried other options on the play store just by searching "shoutcast player" and most did the same thing.

So I tried Poweramp after reading your comment.
With the regex edit it did the same thing, so I disabled it. And without, it kind of does the same thing :/ While "scrobbling now" works, after the track is finished it doesn't add anything to my history/profile. I am listening to the whole song but #194  most songs nowadays are shorter than 4 minutes lol

**Comment by zhutra** [comment]
Well, I just realized how to fix this and you were right about it not having anything to do with the regex.
I went into Pano's settings and changed the scrobble delay to 2 and a half minutes.
It's scrobbling now, even with my workaround enabled.

Thanks :)
