### ISSUE TITLE
Request remove hamburger menu, and move everything to bottom (tab bar)

### ISSUE THREAD

**Issue by Harmonie666** [kawaiiDango/pScrobbler#204]
Moving everything to bottom (tab bar) and removing the cheap, outdated hamburger menu (side drawer) would greatly improve the UI, UX of PanoScrobbler. Please consider doing this. Using the hamburger menu is not enjoyable. The app would be much more intuitive to use with tab/bottom bar.
It could be done similarly to the "finale" app:

https://play.google.com/store/apps/details?id=com.nrubintech.finale

Hamburger menu is considered a outdated, cheap way of developing, and maintining apps. And there are already a few popular services like ExpressVPN that have recently switched over to tab bar in their Android app. It's time to ditch the hamburger menu/side drawer UI.

Example ExpressVPN new bottom tab bar UI:

![Screenshot_20220211-204623242 (1).png](https://user-images.githubusercontent.com/73917917/153659541-9af2126d-9f68-42a2-8348-83488cbd348d.png)

**Comment by kawaiiDango** [comment]
I don't understand how a hamburger menu is cheap or outdated. I think using
it is "not enjoyable" for you because you have gestures enabled and you are
unaware of the additional gestures for the drawer. You need to swipe
diagonally, or long press on the edge and then swipe.

**Comment by Harmonie666** [comment]
The issue is I don't want to swipe or long press as this gestures are more difficult to do and more time consuming with the back and forth, than simply taping on icons at the bottom which are also closer to the fingers.

**Comment by Harmonie666** [comment]
You are refusing to add Tab bar to the app. Got it. Well atleast thanks for the working app. I appreciate everything else :)

This request can be closed.
