### ISSUE TITLE
Check edits after pattern edits

### ISSUE THREAD

**Issue by glacialcascade** [kawaiiDango/pScrobbler#207]
If a pattern edit affects a track, and there is an edit for the pattern-edited-version for that track (which is the default behavior when pressing edit from the scrobble list), the edit will not work for future scrobbles. This may not be very clear so let me illustrate with an example: on Youtube Music, the titles of the [Celeste B-Sides](https://musicbrainz.org/release/f56b2986-1239-4f17-92c2-b17635f14170) scrobble as e.g. "[Official] Celeste B-Sides - 04 - in love with a ghost - Golden Ridge (Golden Feather Mix)". I have a pattern edit to remove the `.* - [0-9]+ - ` at the start, because this also happens with several tracks of the Celeste OST, but this still leaves an incorrect title that includes the artist. So, I have had to edit these individually in the app, but they do not apply to future scrobbles, presumably as the "original title" in the edit is actually the title after the pattern edit ("in love with a ghost - Golden Ridge (Golden Feather Mix)"). Therefore, I am suggesting that edit matching is also checked after pattern edit matching, to correspond to the  behavior of editing the scrobble list. (This specific issue could be fixed with #152 (or indeed just preventing the B-Sides from hitting the regex, which I'm doing), but I presume this could also cause issues with other albums, so I've started an issue.)

**Comment by kawaiiDango** [comment]
Will be implemented in the next update

**Comment by NeoFoxxo** [comment]
any idea when that update will come out?
