### ISSUE TITLE
Add search option for friendslist(following)

### ISSUE THREAD

**Issue by Harmonie666** [kawaiiDango/pScrobbler#208]
When you follow lots of users in LFM it becomes kinda difficult trying to find particular users in the current friendslist. Can "insert username" search field be added to quickly find friends(Following) by username?

![Screenshot_20220301-121955377 (1).png](https://user-images.githubusercontent.com/73917917/156160385-27cdc8ab-68d8-45d0-a80e-0616074dc39a.png)

**Comment by kawaiiDango** [comment]
Not possible
