### ISSUE TITLE
Custom Listenbrainz server not verifying

### ISSUE THREAD

**Issue by jbmfg** [kawaiiDango/pScrobbler#209]
I am running Maloja for scobbling and can see any incoming requests in its logs.  When i use Pano and enter my maloja server's details i see no request on the Maloja side.  When i tap "verify" in Pano it immediately turns to the red circle with line through it.  Its as if its not even attempting to make the request before failing.  

I am using this for the api URL: http://192.168.0.107:42010/apis/listenbrainz
and i enter an api key i know works.  
Click verify and nothing happens except the red circle.  

Am i missing something?

Edit: I've tried both the play store version of Pano and the one linked on this github (v2.53), same results

**Comment by kawaiiDango** [comment]
HTTP (cleartext) is not allowed

**Comment by jbmfg** [comment]
I wondered if that was the case since it seemed to bring up the red circle without taking enough time to have tried anything.  I would make the suggestion of putting that into a warning when it happens.  I would also suggest allowing it in the private address space.

**Comment by kawaiiDango** [comment]
HTTP is not allowed by default since a certain Android version. To opt out
and allow http on local ip ranges, the entire app has to be marked as
insecure. However, I could allow self signed certificates for custom
servers in the future.
