### ISSUE TITLE
Pano Scrobbler on Amazon Fire Tablet

### ISSUE THREAD

**Issue by mighty-boosh** [kawaiiDango/pScrobbler#21]
Hi - Pano Scrobbler is perfect for me on my Android phone. I'd really love to use it to scrobble Tidal streams from an Amazon Fire tablet. Would this be possible do you think? Thanks

**Comment by kawaiiDango** [comment]
Isn't that just another Android device? Why wouldn't it work?

**Comment by kawaiiDango** [comment]
Won't be uploading to Amazon app store. Just get the apk
