### ISSUE TITLE
[Feature Request] Automatically remove featured artist 

### ISSUE THREAD

**Issue by MisterPharaoh** [kawaiiDango/pScrobbler#211]
While scrobbling from Apple Music, some songs have two artists in the artist field like so [Artist 1] & [Artist 2]

It would be nice if Pano Scrobbler had an option to remove the second artist from the artist field automatically, so that last.fm stays well organized and less editing is required.

Thanks a lot for the app, just purchased the premium features to support! Wishing the developer a fantastic day :)

**Comment by kawaiiDango** [comment]
Use https://github.com/kawaiiDango/pScrobbler/issues/177

**Comment by MisterPharaoh** [comment]
> Use #177

Thanks a lot!
