### ISSUE TITLE
Termux - Music Not Detected

### ISSUE THREAD

**Issue by GUUser91** [kawaiiDango/pScrobbler#213]
The termux app won't scrobble.
Here's a image of termux enabled in the settings.
![settings](https://user-images.githubusercontent.com/77461922/160226228-8b8cf4ee-5e85-45d4-8a2f-40be716d3eab.png)

Here's a image of mpv playing a song in termux
![mpv](https://user-images.githubusercontent.com/77461922/160226251-17e58815-4b8a-4fc4-9767-862b6336df31.png)

Here's a image of cmus playing a song in termux
![cmus](https://user-images.githubusercontent.com/77461922/160226268-1a163c68-def0-41d8-891a-8cafd3782137.png)

**Comment by kawaiiDango** [comment]
Only regular android apps are supported
