### ISSUE TITLE
2 second song won't scrobble

### ISSUE THREAD

**Issue by GUUser91** [kawaiiDango/pScrobbler#214]
A 2 second song won't scrobble. Here's an image of the 2 second song being played on the AIMP app.
![2 second song](https://user-images.githubusercontent.com/77461922/160226720-8201ac0a-29d7-46f5-a926-1c3961ed6da8.png)

Here's an image of the 2 second song being displayed on the Pano Scrobbler, but it's not being scrobbled.
![scrobble](https://user-images.githubusercontent.com/77461922/160226735-fd0eead0-cd34-46d5-9697-07aa762ab804.png)

**Comment by kawaiiDango** [comment]
The minimum is 10s
