### ISSUE TITLE
[Meta] Clearer Issue Organization

### ISSUE THREAD

**Issue by ReidZ3** [kawaiiDango/pScrobbler#215]
The current state of organization is lacking.
While development and issue resolution seem fairly unaffected by this, the lack of communication leaves issue submitters wondering when/if their issue is going to be addressed.

Take @pixiekat: it's been over 3 years, and her issue (#13) is still unaddressed.

___

But, I don't like to complain without offering solutions...
I'd love to see some of your labels getting some use, especially:

- https://github.com/kawaiiDango/pScrobbler/labels/bug
- https://github.com/kawaiiDango/pScrobbler/labels/enhancement
- https://github.com/kawaiiDango/pScrobbler/labels/wontfix

And of course, closing out some of the resolved and/or https://github.com/kawaiiDango/pScrobbler/labels/invalid issues would be great!

___

Anyways, sorry if I come off at all as a mom telling you to clean your room 😅
I do really like the app! It's been such a time saver! It's just a little difficult when you have an issue to tell whether or not your bug/suggestion has been or is going to be addressed.
<br />

**Comment by kawaiiDango** [comment]
Finally did it.
