### ISSUE TITLE
App useless if you don't have Last.fm account

### ISSUE THREAD

**Issue by airon90** [kawaiiDango/pScrobbler#217]
You can't do anything if you don't have a Last.fm account, because at the beginning you must sign in to Last.fm before starting using the app. I just use Libre.fm and Listenbrainz so this app is useless

**Comment by Terrance** [comment]
Does the latest release now support using the app without a Last.fm account then?  I just took another look at the app, but as far as I can tell you still need to link a Last.fm account before gaining access to the app for adding other accounts.

**Comment by kawaiiDango** [comment]
No it doesn't. I closed as I will not be implementing this
