### ISSUE TITLE
Auto-detected apps scrobble without confirmation, leaking user data

### ISSUE THREAD

**Issue by Bujiraso** [kawaiiDango/pScrobbler#22]
Hi there,

I have an app which keeps getting redetected as a new app to PanoScrobbler, which is perhaps its own issue and I'll fill out a bug if I haven't done something dumb.
The issue here however is that this app keeps scrobbling to my public last.fm account without me ever accepting it as a scrobbling source.

The data leaked is, right now, not super dangerous or embarassing but a fix should be implemented for the user's sake that these scrobbles are *not* sent to the server and only saved in a pending queue.

Where I don't know how the app is implemented, I must impress how important it is to scrobble them to /dev/null (a joke, I mean "to nowhere") instead of a server while they are not confirmed.

Doubtlessly, the app should even tolerate lost scrobbles before leaked scrobbles

Let me know if there's any more detail needed.

(Steps to reproduce: listen to music on a new app and don't answer PanoScrobbler when it asks if it should scrobble from this app. Check your last.fm -- PanoScrobbler didn't wait before sending)

**Comment by Bujiraso** [comment]
Oh p.s. Thank you for this app -- it's awesome

**Comment by kawaiiDango** [comment]
You need to disable auto detect apps from settings

**Comment by Bujiraso** [comment]
Hi there,
Thanks for your feedback.

So this is not actually what I mean.

I think that "auto-detect apps" is a fine concept, and it can help remind you to add apps to be scrobbled.
They should not be scrobbling *before* the acceptance, though.

Does that make it more clear?

**Comment by kawaiiDango** [comment]
The intended behavior is to accept new apps when auto detect apps is enabled. As long as it scrobbles, most people will ignore the notification. The notification text may be misleading.

**Comment by Bujiraso** [comment]
Ok, perhaps the best solution is to update the text that describes the feature in the settings?
It is on by default? It might be best to turn it off by default.

**Comment by kawaiiDango** [comment]
changed the notification text https://github.com/kawaiiDango/pScrobbler/commit/5f6e7686fbb7c440b0370965cfca04fbc87b61d7
Won't disable auto detect by default, as the average user won't know he is supposed to enable it

**Comment by Bujiraso** [comment]
Sounds good -- thanks :+1:
