### ISSUE TITLE
Include album artist information in the scrobble for tracks that have a different main artist/artists than the album artist

### ISSUE THREAD

**Issue by NomaanMalick** [kawaiiDango/pScrobbler#227]
Is it possible to include the album artist information in the scrobble for tracks that have a different main artist/artists than the album artist?

![image](https://user-images.githubusercontent.com/46681247/170676486-4b42fcee-1334-45ba-97d3-797638ef709d.png)
![image](https://user-images.githubusercontent.com/46681247/170679285-3c921722-167c-44bc-b954-662a607b310d.png)
![image](https://user-images.githubusercontent.com/46681247/170676045-387ec173-c781-4635-b2cb-44a6293518b4.png)

**Comment by kawaiiDango** [comment]
It already does that if the player passes on that info.

**Comment by NomaanMalick** [comment]
Does that mean Apple Music doesn't pass the album artist information to Pano Scrobbler?

**Comment by kawaiiDango** [comment]
Yes
