### ISSUE TITLE
Vanilla player on Miui not scrobbling

### ISSUE THREAD

**Issue by petitminion** [kawaiiDango/pScrobbler#233]
Hello, 

Is scrobbling with VM player working ? It doesn't seem to work in my Miui12 phone :s 

Any idea why ? 

Thx !

**Comment by kawaiiDango** [comment]
If you are talking about https://play.google.com/store/apps/details?id=com.vgng.vmediaplayer it's not possible to scrobble that app

**Comment by petitminion** [comment]
Nop I m speaking about vanilla player : https://github.com/vanilla-music/vanilla
