### ISSUE TITLE
[Feature Request] Order friends based on listening activity

### ISSUE THREAD

**Issue by earthwalker31** [kawaiiDango/pScrobbler#236]
Similar to friend activity in spotify, i think it would make sense to display friends that are currently scrobbling at the top.
This could either be done by default or enabled in the settings

Thank your for your continuous work on this project ^^

**Comment by kawaiiDango** [comment]
This is already implemented. You will need to load everyone's scrobbles by scrolling for the sort button to show up.

**Comment by earthwalker31** [comment]
Ah I see never noticed that button

Thanks ^^
