### ISSUE TITLE
Setting notifications to silent doesn't work in Android 12

### ISSUE THREAD

**Issue by olliebean** [kawaiiDango/pScrobbler#237]
Probably this is an issue with Android rather than the app, but I'm mentioning it here in case there is something that can be done about it. I have set all the app's notifications to silent in the Android settings, but they are still appearing in the top section of the notifications shade, as well as showing on the status bar. No other apps are exhibiting this problem. Phone is Realme 8 5g, just updated to Android 12 (it worked fine with Android 11).

**Comment by kawaiiDango** [comment]
It might have to do with how the OS or adaptive notifications rank them, not something the app can control. You may try to minimize notifications.
