### ISSUE TITLE
Issues with some songs using file names instead of tags 

### ISSUE THREAD

**Issue by yolorag** [kawaiiDango/pScrobbler#239]
For some time and reasons, songs that used to be properly scrobbled. I use the same player as always (jetAudio), haven't changed any settings, both in the player and pScrobbler, didn't change any tags or file names.

Check out the attached screeshot for an example.

![Screenshot_20220731-202322](https://user-images.githubusercontent.com/22390622/182040485-f0d6dea8-1825-44e9-ab69-3f9ceb7adbe9.jpg)

**Comment by kawaiiDango** [comment]
which one is supposed to the tag and which one the file name?

**Comment by yolorag** [comment]
> which one is supposed to the tag and which one the file name?
El Sueno De Morfeo is the artist, "ojos de cielo" and "amor de sal" are the titles. 
Both songs are properly tagged (see attached screenshots) and fallow the same naming pattern for the file names %artist - %title.

It happens rarely and I was able to reproduce it on 2 devices and it's fixed when I make an edit, but I wanted to report it so maybe you can figure out what's wrong cause I'm running out of ideas ^^
![Screenshot_20220802-153835](https://user-images.githubusercontent.com/22390622/182390819-093d6e1e-6006-48c8-aff2-0074049f0d06.jpg)
![Screenshot_20220802-153818](https://user-images.githubusercontent.com/22390622/182390823-548dee78-340b-4e53-aa30-a3080e269a52.jpg)
![Screenshot_20220802-153848](https://user-images.githubusercontent.com/22390622/182390825-2336ede8-0830-4375-baab-32fd0551b298.jpg)

**Comment by kawaiiDango** [comment]
This could be an issue with jetAudio itself, sending the file name in the track title field.

**Comment by yolorag** [comment]
Ok, I don't know cause as I said, the same tracks were scrobbled properly up to some point
