### ISSUE TITLE
[feature request] Song search service: add "YouTube Music"

### ISSUE THREAD

**Issue by aisbergde** [kawaiiDango/pScrobbler#24]
Currently these song search services are implemented: YouTube, Spotify, Google Play, SoundCloud
I miss "YouTube Music".
My issue: I can select the option to search on YouTube but then it needs to be transfered from YouTube to YouTube Music. The integration from YouTube with YouTube Music is not so good, there is no easy way to play videos found on YouTube in YouTube Music.
That's why I would like to search directly on YouTube Music.

**Comment by kawaiiDango** [comment]
Done
