### ISSUE TITLE
Vanilla player on Miui not scrobbling 

### ISSUE THREAD

**Issue by petitminion** [kawaiiDango/pScrobbler#240]
Hello, 
Reopening since last issue closed before I can respond 

Is scrobbling with VM player working ? It doesn't seem to work in my Miui12 phone :s

Any idea why ?

This the repo of vanilla player https://github.com/vanilla-music/

Thx !

**Comment by kawaiiDango** [comment]
I couldn't reproduce this. It scrobbles for me. Check if the scrobbler is getting killed by miui. dontkillmyapp.com

**Comment by petitminion** [comment]
youre are right idk its working now :s thx to have check !

**Comment by petitminion** [comment]
and thx for this great app !
