### ISSUE TITLE
Sticky album info on YouTube music 

### ISSUE THREAD

**Issue by Saragon4005** [kawaiiDango/pScrobbler#242]
Brought up in #200 [here](https://github.com/kawaiiDango/pScrobbler/issues/200#issuecomment-1159817447)

On YouTube play music, if no album info is provided for some reason the album info is assumed to be the same. No idea if this is on the app side of YouTube's fault.

Edit: upon further testing force stopping the app and starting it again gets the info correctly, suggesting this is pano's fault.

**Comment by kawaiiDango** [comment]
It is a youtube music issue

**Comment by kawaiiDango** [comment]
Please send logs from the by reproducing the issue and then clicking Bug Report in the app. Also test with other scrobblers.
