### ISSUE TITLE
[feature request] scrobble YouTube video chapters

### ISSUE THREAD

**Issue by replicaacliper** [kawaiiDango/pScrobbler#243]
Hi. Thank you for the wonderful app, it has been extremely useful in improving my music listening experience.

One feature I'd like to request is the ability to scrobble individual chapters from a YouTube video separately. This would be particularly useful when scrobbling single-video mixes or albums on YouTube or YouTube Vanced. The artist name can be pulled from the chapter title first and then the video name second. I know Web Scrobbler has implemented this feature and it has been very useful in many contexts.

**Comment by kawaiiDango** [comment]
Not possible

**Comment by replicaacliper** [comment]
Pretty late, but why isn't this possible? Web Scrobbler can do it.

**Comment by kawaiiDango** [comment]
Pano only has access to the channel name and video title while Web Scrobbler has access to everything in the webpage
