### ISSUE TITLE
[Feature Request] Create Spotify playlist from charts

### ISSUE THREAD

**Issue by Moelejaan** [kawaiiDango/pScrobbler#247]
Hi,

Long-time and extensive user of panoscrobbler here! Great work!

I was wondering if it would be possible to add the feature to create a Spotify playlist based on a user-selected-time-frame in the tracks chart.

For example, I would choose 1-month as the time period on the tracks chart, then hit the three-dot menu and choose create playlist. This would then open a dialog to set a playlist name and the number of tracks to add to the playlist.

If possible, it would be absolutely amazing if panoscrobbler could keep the created playlist in sync with the changing track chart. (sync could be done once every 24h)

Rationale for the feature: I use two apps to listen to music (one streaming, one local library) and scrobble both for a total overview of what I listen. I like to listen to a playlist of overall most-listened tracks in a certain time period. (so not only based in the streaming or the local library) And not having to update it manually every day would be such a time saver!

I hope you will consider this feature! 

Kind regards!

**Comment by kawaiiDango** [comment]
Spotify features are not planned right now. Also this would need bulk requests to look up every song on Spotify which may hit the rate limits. AFAIK, there are websites that can do what you mentioned.
