### ISSUE TITLE
Album Artist field is not correctly recorded when scrobbling tracks from MediaMonkey for Android

### ISSUE THREAD

**Issue by zachrank** [kawaiiDango/pScrobbler#249]
The album artist for tracks that have different artist and album artist values is not picked up by Pano Scrobbler when listening to music via MediaMonkey on Android (MMA). I've reached out to the MediaMonkey team about this and they claim that they set `android.media.metadata.ALBUM_ARTIST`. Is `android.media.metadata.ALBUM_ARTIST` the correct setting that pScrobbler reads for album artist? If not, what is the correct setting?

Here is a screenshot of my conversation with the MediaMonkey team.
![image](https://user-images.githubusercontent.com/1229811/188596225-373f91a8-e586-41eb-970c-0a776f671e11.png)

According to the ticket #227 pScrobbler should pick up album artist if it is indeed reported. Since this is not happening it seems that one of the following situations is happening:
- MMA does not actually report the album artist
- MMA is reporting the value from the artist field as the album artist
- pScrobbler is not seeing the album artist field from MMA
- pScrobbler is reporting the artist field from MMA as the album artist

I told the MediaMonkey team that I'd reach out to pScrobbler about this next. Is there anything that I can do to help debug this or show proof that the bug is on the MMA side?

For reference, I tested this with MMA 1.4.3.0950 on a Samsung Galaxy S10 running Android 12 and One UI 4.1 and the latest version of pScrobbler.

**Comment by kawaiiDango** [comment]
According to https://github.com/kawaiiDango/pScrobbler/blob/32fdf8c0c4727d79a410701b4a1809067edf8381/app/src/main/java/com/arn/scrobble/SessListener.kt#L217 , pano reads the album artist

I also tried printing the mediamonkey metadata for the following file:
![Screenshot_20220906-184456_MediaMonkey](https://user-images.githubusercontent.com/1066519/188646591-dd8136ae-2fe3-4092-9903-3d8646ad568c.png)

I got this:


        android.media.metadata.ALBUM_ART: android.graphics.Bitmap@201716a
        android.media.metadata.ARTIST: ayame
        android.media.metadata.NUM_TRACKS: 1
        android.media.metadata.DISPLAY_SUBTITLE: ayame
        android.media.metadata.DURATION: 315400
        android.media.metadata.DISPLAY_TITLE: DAYS
        android.media.metadata.MEDIA_ID: 1
        android.media.metadata.TRACK_NUMBER: 1
        android.media.metadata.ALBUM: CLOUD 9
        android.media.metadata.TITLE: DAYS
        android.media.metadata.ALBUM_ARTIST: ayame

**Comment by zachrank** [comment]
> I also tried printing the mediamonkey metadata for the following file: ...
> 
> I got this:
> 
> ```
>     android.media.metadata.ALBUM_ART: android.graphics.Bitmap@201716a
>     android.media.metadata.ARTIST: ayame
>     android.media.metadata.NUM_TRACKS: 1
>     android.media.metadata.DISPLAY_SUBTITLE: ayame
>     android.media.metadata.DURATION: 315400
>     android.media.metadata.DISPLAY_TITLE: DAYS
>     android.media.metadata.MEDIA_ID: 1
>     android.media.metadata.TRACK_NUMBER: 1
>     android.media.metadata.ALBUM: CLOUD 9
>     android.media.metadata.TITLE: DAYS
>     android.media.metadata.ALBUM_ARTIST: ayame
> ```

Huh, then it would seem that MediaMonkey is indeed broadcasting `android.media.metadata.ALBUM_ARTIST` as their support team said but its reporting the wrong value for the album artist. I'll bring this issue back up with the MediaMonkey team. Thanks for debugging/verifying on your side @kawaiiDango!

**Comment by zachrank** [comment]
In case anyone is wondering, I've followed up with the MediaMonkey team on this. They've confirmed that they're setting the value for `ALBUM_ARTIST` incorrectly and that it will be included in an upcoming beta version of the app. Here is a link to the issue in their bug tracker: https://www.ventismedia.com/mantis/view.php?id=19359

Here is a screenshot of my conversation with them.
![image](https://user-images.githubusercontent.com/1229811/189274139-3ee944d1-9e09-46d1-b5db-49a625aea59b.png)
