### ISSUE TITLE
Scrobble from microphone continuous mode

### ISSUE THREAD

**Issue by Icchy92** [kawaiiDango/pScrobbler#252]
Hello, do you think it would be possible to scrobble automatically and continuously from the microphone?
For example if there's music in the room, or in your friend's car and you want to keep track of it.
For what I saw your app is pretty fast at recognize the songs, so maybe the difficult here is how to know when a new one appears? 
Thanks in advance!

**Comment by kawaiiDango** [comment]
This will not be implemented with ACRCloud because of the large number of
network queries it would generate. You can use Autoshazam or Pixel Now
Playing (Ambient Music Mod for non Pixel devices) which can listen
continuously. Pano can track the notifications posted by those apps and
scrobble them.

**Comment by Icchy92** [comment]
Hi, thanks for the reply. Sadly I can't get shazam and your app to communicate, notification access is enabled and autoshazam actually works as it should, so I don't understand why Pano doesn't recognize it. Using another app to directly play music has no problem. 
I'm using android 5.1.

**Comment by Icchy92** [comment]
I don't like that very much but it does the work. I'll try again your app with the next phone I'll buy, thanks!
