### ISSUE TITLE
Exclude Audio Streams?

### ISSUE THREAD

**Issue by RudeBoyEEEE** [kawaiiDango/pScrobbler#254]
I want to only scrobble the actual music I have on PowerAmp, as opposed to the streams I listen to on the app as well. Is there a way to exclude stream links from the Scrobbling? It picks up the songs anyway. Thanks in advance!

**Comment by kawaiiDango** [comment]
I don't think this can be implemented in a reliable way.

I have noticed that Poweramp puts the name of the radio station in the album field. You can use Block Metadata to block an album name

**Comment by RudeBoyEEEE** [comment]
That doesn't seem to do it. Do you think Tasker could stop scrobbling with those files, then start again when I play any different one?

**Comment by kawaiiDango** [comment]
You need to check if the duration of the currently playing track in
Poweramp is greater than 0, if not, broadcast Pano's cancel intent (copy
from pano settings) to cancel those scrobbles. You probably need
autonotifications. This cannot be generalized for all music apps as some do
not provide the duration for songs even if they are local files.

**Comment by RudeBoyEEEE** [comment]
I'll look into that and let you know if it works. For the moment, I've switched to a different app that also allows audio streams, but without scrobbling that app (Podcast Addict).
