### ISSUE TITLE
Fast song like in a notification

### ISSUE THREAD

**Issue by danyyok** [kawaiiDango/pScrobbler#256]

**Comment by kawaiiDango** [comment]
Not sure what you mean

**Comment by danyyok** [comment]
> Not sure what you mean

I think that: pano scrobbler should detect that the music is playing (scrobbbled tracks / what i scrobb now) and you can quickly like this track, no, I'm not talking about a notification that has a name and just a like (a function that takes metadata from the notification) 
I'm sorry if I misunderstood the text, I use google translate

**Comment by danyyok** [comment]
> > Not sure what you mean
> 
> I think that: pano scrobbler should detect that the music is playing (scrobbbled tracks / what i scrobb now) and you can quickly like this track, no, I'm not talking about a notification that has a name and just a like (a function that takes metadata from the notification) 
> I'm sorry if I misunderstood the text, I use google translate

**Comment by danyyok** [comment]
> Not sure what you mean

pano scrobbler should collect songs from list of listened songs (scrobbled,what i scrobb now)

**Comment by danyyok** [comment]
> Not sure what you mean

It would be nice to delete scrobb (это не сильно важно,мне главное быстро лайкать что я сейчас скробблю/заскробблил)
