### ISSUE TITLE
App not scrobbling

### ISSUE THREAD

**Issue by Aroooxxx** [kawaiiDango/pScrobbler#257]
I have issues with scrobbling. On last Tuesday i used app as usual, but next day I noticed that songs I listented were not scrobbled. I reinstall pano and it works, but is it the way to add lost songs to last FM library? 
I use Spotify and i had not made any actions to broke scrobbling

**Comment by kawaiiDango** [comment]
Since uninstalling and reinstalling deleted the data including the pending
scrobbles, there is no way to get them back
