### ISSUE TITLE
Musiccast internet radio - artist incorrectly identified

### ISSUE THREAD

**Issue by tpluscode** [kawaiiDango/pScrobbler#27]
Here's a screenshot showing Musiccast playing internet radio.

![Screenshot_2019-03-13-10-34-37-148_com miui home](https://user-images.githubusercontent.com/588128/54269557-d8151680-457d-11e9-9249-ef7b4ca46d7e.png)

The entire `[artist] - [title]` appears in the first line. The second line seems to be the radio station name every time.

**Comment by kawaiiDango** [comment]
Musiccast is using the metadata fields incorrectly, probably contact it's dev?

**Comment by tpluscode** [comment]
So, Pano Scrobbler only relies on metadata, it doesn't ever attempt to parse the notification text?

Sorry if it's a naive questions, I know next to nothing about Android development.

**Comment by kawaiiDango** [comment]
It only reads metadata from MediaSession of other apps, and for that it needs notification access. That's how it is on Android, even though they aren't related to notifications.
