### ISSUE TITLE
Podcast Addict 2022.7.6 and PanoScrobbler 2.73 have the album name in the artist field

### ISSUE THREAD

**Issue by djryan** [kawaiiDango/pScrobbler#272]
Since I updated one of these apps, I have to manually edit in the artist field.  Sent logs/bug report on October 8th.

**Comment by kawaiiDango** [comment]
The report didn't have the logs attached, maybe you accidentally removed it?

**Comment by djryan** [comment]
Ah, my email client stripped the attachment.  Another two bundles on their way now - one for an episode with bookmarks and one without.
