### ISSUE TITLE
'Love' option is not working after the last update

### ISSUE THREAD

**Issue by Ruke805** [kawaiiDango/pScrobbler#275]
After the last update, I noticed that Love option is not working, it shows the animation when, but after a few seconds the Love icon disappears and it's not completed. I've tried with "Listening now" mode and with tracks already scrobbled, both ways have not worked. 

I recorded a video showing the issue. 

thanks in advance.

https://user-images.githubusercontent.com/62116034/196011534-5fed9c4b-1de2-4627-adfd-1711dc51145d.mp4

**Comment by Ruke805** [comment]
I've attached the log file as well

[log.txt](https://github.com/kawaiiDango/pScrobbler/files/9793319/log.txt)

**Comment by kawaiiDango** [comment]
I couldn't reproduce it.
