### ISSUE TITLE
Music having incorrect Cases

### ISSUE THREAD

**Issue by RuthlessRuler** [kawaiiDango/pScrobbler#279]
Hey,
So irrespective of the source I scrobble, Some music have wrong case, Eg. Lavendar Haze From Taylor Swift appears as lAveNDER hAZe after the music is submitted as scrobbled.

Similar with Snow On the Beach and etc music. I tried uninstalling & reinstalling the app. (Btw, there are no Edits for this song too.

**Comment by kawaiiDango** [comment]
This is not a bug with the app

**Comment by RuthlessRuler** [comment]
> This is not a bug with the app

It's very weird cause that's how this appears:
![Screenshot_2022-11-04-01-56-46-150_com arn scrobble](https://user-images.githubusercontent.com/20885012/199827182-900a3c38-50de-40af-ad0c-05f431f299ca.jpg)
