### ISSUE TITLE
Windows 10/11 Phone Link picks up Pano instead of the actual player

### ISSUE THREAD

**Issue by hugalafutro** [kawaiiDango/pScrobbler#280]
Hi, 
not really sure this is issue with Pano, but maybe you/someone may have some insight:

I was playing around with the Win11 Phone Link app and when I enable the Audio Player function it's supposed to pick up the notification from phone media player and show the info in the Phone Link app, but the app picks up Pano scrobbler notification instead of the media player (Symfonium)

![image](https://user-images.githubusercontent.com/30209689/199971100-6c22aa15-c151-4fa1-9719-42511f6bf09f.png)

Any suggestion welcome, thanks :)

**Comment by kawaiiDango** [comment]
Pano uses a media style notification (meant for music players) to display
the love and cancel buttons. Music players also have a media session
attached to the notification while they are playing media, Pano doesn't.
But it looks like Phone Link doesn't check for that.

You could add pano to some ignore list if Phone Link has one, or uncheck it
in "See all Apps" in notification access settings in recent versions of
Android

**Comment by hugalafutro** [comment]
Thanks for the suggestions I did some adjusting in settings you mentioned, and it sort of works now 75% of the time every time. 

I think it's the microsoft app being dodgy though. It stopped picking up Pano, but doesn't always pick up Symfonium, but that's beside the point of this discussion :) I get it looking like this when it works:

![image](https://user-images.githubusercontent.com/30209689/200119001-f853a2e8-598f-43cd-ac80-3af48052e3c3.png)

Overall, microsoft apps being what they are, the Phone Link is much more usable than I'd expect honestly.
