### ISSUE TITLE
The icon looks weird in android

### ISSUE THREAD

**Issue by ilysnemo** [kawaiiDango/pScrobbler#282]
![IMG-20221114-WA0000](https://user-images.githubusercontent.com/58479574/201540031-7d3b8a66-296c-4389-ad1b-7b4f1e68e90e.jpg)

I've installed your app yesterday but the icon looks weird that makes me uncomfortable lol. Did you will fix it on the next update?

**Comment by kawaiiDango** [comment]
No. This is a launcher bug. Use a different launcher.
