### ISSUE TITLE
PanoScrobbler stopped working on my TCL TV from VRadio app

### ISSUE THREAD

**Issue by dariusz-wozniak** [kawaiiDango/pScrobbler#283]
PanoScrobbler stopped working on my TCL Tv from VRadio app.

PanoScrobbler 2.81
VRadio 1.1.5
Android TV OS 11 4.9.116+
TCL 55C728

The following message appears.
When I click on the power savers option then the web browser opens and nothing happens.
When I click on battery optimization nothing happens.

![image](https://user-images.githubusercontent.com/5969160/202134112-d2cd1535-2e94-4677-af41-2c58c6fb017a.png)

**Comment by kawaiiDango** [comment]
https://telegra.ph/Pano-Scrobbler-FAQ-05-30 , first point
