### ISSUE TITLE
[Feature Request] Ignore Tags

### ISSUE THREAD

**Issue by UserNo84** [kawaiiDango/pScrobbler#289]
Hi!

I've just spent 7,49 Euro just to find out that "block metadata" does not what I expected it would do. I assumed that scrobbles with selected metadata are simply not submitted to Last.fm. Could you add this as a third option to select? I don't want the app to mute or skip my stuff, just to not scrobble certain things without me enabling and disbling the entire scrobble function all the time.

**Comment by kawaiiDango** [comment]
Uncheck both mute and skip

**Comment by UserNo84** [comment]
That works. Thanks!
