### ISSUE TITLE
After update on 03/21 won't scrobble at all

### ISSUE THREAD

**Issue by ItDoesntMatter** [kawaiiDango/pScrobbler#29]
Hey,

I just updated pScrobbler to the latest version available on the App store and now it won't scrobble at all anymore. :-(
I already rebooted my phone, uninstalled it, reinstalled, logged off & into my Last.fm account, but nothing will work.

I've got a Galaxy S9 with the latest Android 9 and patch from March 1.

Any idea why this is happening?
It worked without any problems earlier today before I did the update. :-(

Thank you very much!

**Comment by kawaiiDango** [comment]
Is it working now?

**Comment by ItDoesntMatter** [comment]
Yes, it is working perfectly again. :-)
