### ISSUE TITLE
AOTY: Filter albums on release year

### ISSUE THREAD

**Issue by Moelejaan** [kawaiiDango/pScrobbler#293]
It's almost the same as the current 'year' filter for albums, but instead of looking at all album scrobbles from a specific year, it looks for scrobbles from albums of a certain release year and shows the total amount of scrobbles for those albums. 
Iirc that info is available with the last.fm api. It's a nice Album Of The Year chart :)

**Comment by kawaiiDango** [comment]
release year is not available in the last.fm api
