### ISSUE TITLE
Doesn't detect a song on YouTube

### ISSUE THREAD

**Issue by VA5H-One** [kawaiiDango/pScrobbler#298]
Hi, when I play a music (e.g. https://www.youtube.com/watch?v=3hLd3xA7GJQ) it don't recognize. 
Only works if go to detect a song with the mic.

And I was watching the logo application and I made a logo proposal. If you have an interest, please let me know.

**Comment by CennoxX** [comment]
Are you playing the song with the YouTube app or the browser? Do you have the specific app set in the preferences to scrobble from?
