### ISSUE TITLE
Scrobbling Amazon music is flaky

### ISSUE THREAD

**Issue by Hobby-boy** [kawaiiDango/pScrobbler#30]
I've been having problems scrobbling Amazon Music with Pano, mainly with playlists. 
Scrobbling one track goes through fine, but if I start a playlist or the radio on Amazon music, only the first track properly scrobbles and it's random for the rest. Simple Last.fm scrobbler also has a similar issue with Amazon music.

**Comment by kawaiiDango** [comment]
Bug in Amazon music
