### ISSUE TITLE
[Feature Request] Pano Scrobbler Wear OS app for Smartwatches

### ISSUE THREAD

**Issue by jusuchin85** [kawaiiDango/pScrobbler#301]
With the ability to have music apps on a Wear OS device (Pixel Watch, Fossil Gen6 etc), it would be nice to have playing music scrobble to last.fm — especially the 4G/LTE models where people don't take their phones while exercising.

**Comment by kawaiiDango** [comment]
I don't think it is even possible to grant notification access to an app running on the watch. And I don't own a Wear OS device yet.

**Comment by jusuchin85** [comment]
That's alight @kawaiiDango ! Thanks for looking into it 😃
