### ISSUE TITLE
Cannot compile: resource string/pref_lastfm_disable_desc not found.

### ISSUE THREAD

**Issue by zCri** [kawaiiDango/pScrobbler#306]
```
Android resource linking failed
com.arn.scrobble.app-main-62:/xml/preferences.xml:258: error: resource string/pref_lastfm_disable_desc (aka com.arn.scrobble:string/pref_lastfm_disable_desc) not found.
com.arn.scrobble.app-main-62:/xml/preferences.xml:258: error: resource string/pref_lastfm_disable (aka com.arn.scrobble:string/pref_lastfm_disable) not found.
error: failed linking file resources.
```

Cannot find those resources in the github repo either, if i add them i am also missing other resources such as num_scrobbles_nav, lastfm_reports, song_format_string

**Comment by kawaiiDango** [comment]
I updated the strings for early translation without uploading the code.
This commit should be buildable
https://github.com/kawaiiDango/pScrobbler/commit/4b51f4ff050d9daf5b7f42cf8d3a0cca0b164d89

You will also need https://github.com/kawaiiDango/pScrobbler/issues/219

**Comment by zCri** [comment]
Thanks
