### ISSUE TITLE
Can't connect to libre.fm

### ISSUE THREAD

**Issue by S4bg0** [kawaiiDango/pScrobbler#318]
Hi,

Since a few days, I can't connect my libre fm account to the app. I tried several times. My login is correct. When I submit my libre fm login to the app, nothing happens. Is this an API issue? Thanks.

**Comment by kawaiiDango** [comment]
There has been a login migration bug. Try logging out of all the services and logging in again.

**Comment by jwflory** [comment]
I ran into the same issue with Libre.fm. After reading this, I signed out of Last.fm and Libre.fm, and tried signing back into both. I logged into both services and the app didn't update that the accounts were connected. Then, I force stopped the app and cleared the cache from Android settings. When I reopened the app, Last.fm and Libre.fm connections were there and I confirmed they were both working on the platforms.

**Comment by kawaiiDango** [comment]
A fix for the migration bug has been implemented
