### ISSUE TITLE
listenbrainz error UnknownServiceException

### ISSUE THREAD

**Issue by vv211** [kawaiiDango/pScrobbler#322]
I get a notification with each listen:

"Saved as a pending scrobble
LISTENBRAINZ: UnknownServiceException"

it still scrobbles to ListenBrainz but doesn't save the likes/loves

**Comment by vv211** [comment]
so, inside the app itself there's no indication of any issue

I went ahead and re-entered my ListenBrainz auth token anyway and the error in the notification persists. however, likes are synced to listenbrainz after the song ends and the next song scrobbles

**Comment by kawaiiDango** [comment]
Did you log out of all the services that were logged in?

**Comment by vv211** [comment]
i tried that as well. signed out of all services, closed and force stopped the app, then signed back in; the error remains

**Comment by vv211** [comment]
i haven't seen the error again, so I'll say that signing out of everything fixed it
