### ISSUE TITLE
Samsung TV Tizen Support

### ISSUE THREAD

**Issue by maxelo** [kawaiiDango/pScrobbler#323]
Love your app! been using it from the start. I went for the paid version 2 years ago.
Now that you have support for Android TV and Google TV (Chromecast) I can scroble on almost anything.
I would like to know if there is any chance you could support Samsung TV with their Tizen OS software?

Thanks for your work! 😊

**Comment by kawaiiDango** [comment]
No. Pano Scrobbler is an Android app and always will be
