### ISSUE TITLE
What is this circle that appears above some timestamps on certain tracks?

### ISSUE THREAD

**Issue by frozenpandaman** [kawaiiDango/pScrobbler#327]
Absolutely can't figure this out and don't know where else to ask. Thanks!

![image](https://user-images.githubusercontent.com/7245874/236014761-89c20707-b4dc-480f-94fd-3b750b8fb4f9.png)

**Comment by kawaiiDango** [comment]
Yes they are day seperators, shown above the last scrobble of each day

**Comment by frozenpandaman** [comment]
Thanks! Obviously not very high priority, but being able to turn them off in settings might be a nice feature! :)
