### ISSUE TITLE
System UI Crash

### ISSUE THREAD

**Issue by MSOB7YY** [kawaiiDango/pScrobbler#329]
not sure if it's only in my side, but after updating to `2.93 - 2023, May 01`, the System UI crashes whenever i open panoScrobbler, app itself works properly and other apps work too, only navigations, notification swipes are jittering/lagging too much (unusable)

I'm on Xiaomi redmi note 10 (Android 11 | Cherish OS 2.10)

**Comment by kawaiiDango** [comment]
This could be an OOM. Please send a bug report with logs from the app
