### ISSUE TITLE
Crashing app

### ISSUE THREAD

**Issue by Botanistt** [kawaiiDango/pScrobbler#33]
For a while the app has been crashing for me randomly.
It could be working fine for a while, but then randomly it will crash and won't scrobble.
Once I re-open the app it says "Pano Scrobbler died", or something a long the lines.

I have OnePlus 6T and I have battery optimization for this app disabled.

**Comment by kawaiiDango** [comment]
Send a bug report from the app after a crash

**Comment by Botanistt** [comment]
I have already emailed you the report twice.  I sent another report two days ago. Please take a look!

**Comment by kawaiiDango** [comment]
The one without a description?

**Comment by Botanistt** [comment]
Yes, sorry about that. I sent the report as I was in a rush. Totally forgot to add a description. My bad.

**Comment by kawaiiDango** [comment]
There's no crash in the logs. Send a bug report after it crashes. Also, logs too old get deleted by Android

**Comment by kawaiiDango** [comment]
There are no crashes in the log. Oxygen os is known to kill background processes to save battery. There are a few whitelisted apps like Facebook, WhatsApp etc which do not get killed in the background. Check if disabling advanced optimizations or other  OnePlus settings solves this.

**Comment by Botanistt** [comment]
I have already disabled battery optimisation and it still died from time to time. It wasn't a problem two months ago.
________________________________

**Comment by kawaiiDango** [comment]
Check if disabling advanced optimizations or other OnePlus settings solves this.

**Comment by kawaiiDango** [comment]
https://cdn.guidingtech.com/imager/media/assets/214823/How-to-Fix-OnePlus-Battery-Optimization-Reset-Issue-5_4d470f76dc99e18ad75087b1b8410ea9.png?1548337229

**Comment by Botanistt** [comment]
Hello.

I have disabled that setting and tested the app for over a week. It hasn't crashed ever since I disabled the setting. Thank you
________________________________
