### ISSUE TITLE
What does this icon mean? 

### ISSUE THREAD

**Issue by flexagoon** [kawaiiDango/pScrobbler#335]
I recently started seeing this grey circle on some of my scrobbles. What does that mean?

![Screenshot_20230526-003822~2](https://github.com/kawaiiDango/pScrobbler/assets/66178592/8a426c7b-b164-4cc5-acb9-6fa6109469f8)

**Comment by AminurAlam** [comment]
seperator for different days

**Comment by flexagoon** [comment]
Makes sense, thanks.
