### ISSUE TITLE
`Album Version` pattern edit doesn't work on album

### ISSUE THREAD

**Issue by AminurAlam** [kawaiiDango/pScrobbler#336]
the pattern edit called `Preset: Album Verion` is only tured on for tracks
![8e7 g3m3](https://github.com/kawaiiDango/pScrobbler/assets/64137875/cfab3c9c-e008-4192-898d-310c0c3ffb68)

**Comment by UserNo84** [comment]
"Album version" is a tag only on songs. Why would you use it on albums? This makes no sense.
