### ISSUE TITLE
"Support this app" button doesn't work

### ISSUE THREAD

**Issue by SydneyNS** [kawaiiDango/pScrobbler#337]
I want to "tap to block and skip" songs, but the support button doesn't work when I tap it, it does absolutely nothing when I tap it.

**Comment by kawaiiDango** [comment]
Please send a bug report from the app, shortly after that happens

**Comment by kawaiiDango** [comment]
According to Crashlytics, this seems to be happening to users whose Google Play Services is not up to date. The app uses the billing library 6 which was only released in May 2023.
