### ISSUE TITLE
Some artists images not showing, but in last.fm the artist has the image

### ISSUE THREAD

**Issue by yanlobianchi** [kawaiiDango/pScrobbler#339]
In some artists, the image is unavailable, but in last.fm the artist has a image. As in the example below:
![Screenshot_2023-06-01-15-54-23-658_com.arn.scrobble-edit.jpg](https://github.com/kawaiiDango/pScrobbler/assets/24674211/a8d4851b-bf22-4c50-b4ba-244860f27a39)

![Screenshot_2023-06-01-15-55-36-047_com.opera.browser-edit.jpg](https://github.com/kawaiiDango/pScrobbler/assets/24674211/1c14ee1b-80c2-426d-8968-33f4cd6c0a00)

![Screenshot_2023-06-01-15-55-59-326_com.opera.browser-edit.jpg](https://github.com/kawaiiDango/pScrobbler/assets/24674211/30e764ec-9568-485e-986e-e6c988d8da7f)

**Comment by kawaiiDango** [comment]
Artist pictures are sourced from Spotify because the last.fm API does not provide them. Due to the implementation, the artist's name must have an exact match on Spotify. Sometimes, language differences between the name on last.fm vs Spotify cause this issue.
