### ISSUE TITLE
[Feature Request] Only scrobble youtube videos with the "Music" tag

### ISSUE THREAD

**Issue by cyatek** [kawaiiDango/pScrobbler#34]
I realize I can stop scrobbles manually but whenever I'm not paying attention and just watching random videos I end up scrobbling some non-music videos that somehow end up on the LastFM database. Like [this](https://gyazo.com/6f3119318e3ca954e2ef49bf545b4a51).

If it isn't too complicated to add I'd really welcome a feature similar to [WebScrobbler's](https://i.gyazo.com/4548eb53f6fe713ee98702bf28dc92c5.png) .

Other than that, thanks for the app, it's great!

**Comment by kawaiiDango** [comment]
That's a browser extension, it has access to the HTML content on the page. Can't do that on Android
