### ISSUE TITLE
scrobble edit issue / empty album data is filled by previous song's album

### ISSUE THREAD

**Issue by altruistdevil** [kawaiiDango/pScrobbler#344]
**Describe the bug**
the album of a song carries on to the next song that doesn't have an album data, which makes the scrobble edit i made for it useless
![Screenshot_20230617-221134_Pano Scrobbler](https://github.com/kawaiiDango/pScrobbler/assets/104401868/0635740b-d494-4516-9697-5452dd40e4a0)
![Screenshot_20230617-221229_Pano Scrobbler](https://github.com/kawaiiDango/pScrobbler/assets/104401868/87f7132f-052d-444d-ab5b-bd676c0f0b2d)

**Steps to Reproduce**
Play an official yt music release song (one that has album data), then queue a music video next (youtube video). the previous song's album will be put on the music video's scrobble, instead of having it empty

**Additional info**
essentially, i just want the metadata edits i made to work.. please and thankyou 🥺

it works if i play the song with empty album data first, upon opening youtube music, but if i played a normal song with complete metadata, then the video song next, it won't because it puts the previous song's album on scrobble

**Comment by kawaiiDango** [comment]
Afaik, this is a YouTube music bug and this happens with all scrobblers

**Comment by altruistdevil** [comment]
okay :c thankyou
