### ISSUE TITLE
Simple Scrobbler or Pano Scrobbler for Iphone, please

### ISSUE THREAD

**Issue by matizealves** [kawaiiDango/pScrobbler#345]
Hey, I'm changing from Android to iPhone, but I'm having trouble choosing an app for scrobbles, unfortunately I couldn't find Simple Scrobbler and Pano Scrobbler, the ones that appear when I search are nor working well, and doesn't have all the features these both have... Is there any chance at least one of them are gonna be available for Iphone? Or any other way I can download them? It's horrible to scrobble automatically from Spotify because all the tags are wrong with the ones I use... Anyone with the same problem?

Thanks.

**Comment by kawaiiDango** [comment]
#95

**Comment by hans-juergen** [comment]
If you want to scrobble Spotify on an iPhone, you don't nee an external scrobbling app at all, as the feature in your connected Last.fm apps is independent from the device. In case you refer to featured artists on Spotify being scrobbled as combined artists with other Android apps, the Last.fm method only scrobbles the first artist and ignores the second one listed with a comma.
