### ISSUE TITLE
scrobble videos to Trakt

### ISSUE THREAD

**Issue by kranix0** [kawaiiDango/pScrobbler#346]
Amazing app! Would it be possible to scrobble videos to [Trakt](https://trakt.tv/)?

This is possible on Android and Android TV if I play through Kodi, but not if I play through Netflix, Disney Plus, ABC iView, etc.

**Comment by kawaiiDango** [comment]
Scrobbling movies is out of scope for this project. But anyways, I had checked Netflix and Amazon videos, the metadata provided by them aren't consistent unlike most music players
