### ISSUE TITLE
Tag removal button does not work

### ISSUE THREAD

**Issue by Nixinova** [kawaiiDango/pScrobbler#349]
By tag I mean the genre tagging feature

**Describe the bug**

Tapping the ✖️ to remove a tag does not actually remove it.

**Steps to Reproduce**

1. Tap a song
2. Tap the tags button 🏷️
3. Add a tag
4. Remove it ✖️
5. Exit out
6. Repeat steps 1 & 2 and you will see the tag is still there

**App version**
v2.97

**Additional info**
Bug has existed for a while now.

**Comment by kawaiiDango** [comment]
This eill be fixed in the next update

**Comment by Nixinova** [comment]
:+1: Thanks
