### ISSUE TITLE
Relative times of scrobbles are not updated 

### ISSUE THREAD

**Issue by Nixinova** [kawaiiDango/pScrobbler#350]
**Describe the bug**

When you close out of the app and go back in, older relative times are not updated.

![Screenshot_20230708-145406.png](https://github.com/kawaiiDango/pScrobbler/assets/42429413/808af835-3f6e-42e9-9b9a-be336bb48ab7)

**Steps to Reproduce**

Listen to songs, open the app, listen to some more, open the app again, sometimes the times are not updated.

**App version**
v2.97

**Additional info**

**Comment by kawaiiDango** [comment]
Should be fixed now
