### ISSUE TITLE
Predictive back gesture behaviour in settings page

### ISSUE THREAD

**Issue by JurianOnderwater** [kawaiiDango/pScrobbler#351]
**Describe the bug**
The back gesture behaves a bit strange in the app, especially on the settings page, is where I noticed. When you swipe from the side to go back to the main page it immediately goes back instead of waiting for the swipe being released. If you hold your finger on the screen after the swipe and release after a little bit, the whole app closes, as if it registered a new back gesture. 

**Steps to Reproduce**
- Go to settings page
- swipe from the side of the screen to go back

**App version**
v3.1, 2023 8 jul

**Additional info**
Predictive back on the main page works as expected.

**Comment by kawaiiDango** [comment]
Yes, this is probably a library bug. Those libraries are still in alpha.

**Comment by kawaiiDango** [comment]
In app predictive back has now been disabled until the libraries fully add support for it
