### ISSUE TITLE
Sonos Scrobbling Glitches When Song Ends.

### ISSUE THREAD

**Issue by koalcosadk** [kawaiiDango/pScrobbler#352]
**Describe the bug**
Scrobbling on Sonos works until the song ends. Once a song ends and another track starts, the notification refreshes, but Pano still says it's scrobbling the previous track.

Video of it happening can be found [here](https://youtu.be/aDNoMen6GrU)  (YouTube link)

**Steps to Reproduce**
Play a song to a Sonos speaker via the app and have Sonos enabled in the Pano Scrobbler settings.
Go into an app and wait until a song scrobbles then ends.

**App version**
3.1 - July 8

**Additional info**
This only happens when scrobbling with Sonos, any other app works fine.

**Comment by kawaiiDango** [comment]
Please send a bug report from the app, shortly after this happens, as I do not have a Sonos device to test.

**Comment by koalcosadk** [comment]
Realized the issue is on my end, not Pano's. Will be closing. Sorry for the inconvenience and thank you for the amazing app!
