### ISSUE TITLE
[Feature Request] Block/skip after scrobbling

### ISSUE THREAD

**Issue by SydneyNS** [kawaiiDango/pScrobbler#354]
I am definitely enjoying the block feature, although there's no option to block after a track has been scrobbled. The only way to do it is to press the rewind button and then do it, which is annoying when you have to do it so often.

I'd like there to be an option to do this via the 3 dots on the right side of the scrobble display list in the app, I'd also like this option in the persistent notification at the top.

**Comment by kawaiiDango** [comment]
Implemented
