### ISSUE TITLE
Split Full Album Scrobbles

### ISSUE THREAD

**Issue by Aeyk** [kawaiiDango/pScrobbler#355]
**Is your feature request related to a problem, or particular use cases? Please describe.**
I listen to full albums on YouTube (via NewPipe) and Pano Scrobbles the album information incorrectly the album as the track listing.
If my description isn't clear, see this issue https://github.com/web-scrobbler/web-scrobbler/issues/1682 for additional informatioon. 

**Describe the solution you'd like**
I'd like it to detect 'full album' in the track name and then search ListenBrainz for the album, and scrobble the individual tracks based on how long I listen to the album. Some youtube videos have track listing time in the comments or the video description, but I'm not sure if this application has access to that information. 

**Additional info**

**Comment by kawaiiDango** [comment]
See #243

Detecting 'full album' in the track name and then searching ListenBrainz for the album makes a lot of bad assumptions. The app does not have access to video description or chapters.
