### ISSUE TITLE
Heos app

### ISSUE THREAD

**Issue by matysiewsky** [kawaiiDango/pScrobbler#36]
Is it possible to add support for scrobbling tracks playing in HEOS app?

**Comment by kawaiiDango** [comment]
It probably doesn't send the metadata

**Comment by kawaiiDango** [comment]
I don't have the hardware to test

**Comment by matysiewsky** [comment]
Can I help somehow to check that?

**Comment by kawaiiDango** [comment]
Send a bug report while playing something on that app

**Comment by matysiewsky** [comment]
Already sent

**Comment by kawaiiDango** [comment]
The big report does not contain anything about any music player. Either the player doesn't send any data, so it cannot be scrobbled, or you didn't use the player while sending the report
