### ISSUE TITLE
Unable to resolve a hostname 

### ISSUE THREAD

**Issue by Amovieguy2004** [kawaiiDango/pScrobbler#360]
![Screenshot_2023-08-03-18-04-06-953-edit_com arn scrobble](https://github.com/kawaiiDango/pScrobbler/assets/141337461/df33d8b9-ca95-4f97-b284-118000f7dc18)

This thing was happening since last week and still to this day, it's going on and on. Could you help to fix it?

**Comment by kawaiiDango** [comment]
Check if the app has appropriate permissions to run in the background and open network connections.
