### ISSUE TITLE
Crashing app

### ISSUE THREAD

**Issue by simori4h** [kawaiiDango/pScrobbler#365]
I have a long time problem with this app, I always get the "Scrobbler was killed by your system" error and it keeps happening even though I turn off battery optimization.  And in the case of following the same steps of "Don't kill my app" the same thing continues to happen.  my device is a Redmi A2 version Android 13 go edition.  I would like you to help me solve this problem, since it is the only application that does an excellent job.

versión 3.6 - 2023, Aug 16

Redmi A2 versión Android 13 
![Screenshot_20230819-084436](https://github.com/kawaiiDango/pScrobbler/assets/142670898/0d873e0a-db6f-4be6-a5cf-189a05d568aa)

**Comment by kawaiiDango** [comment]
This is a MIUI issue and not an issue with the app. I don't know if there are any solutions if the ones listed on dontkillmyapp didn't work as I am not much familiar with MIUI.
