### ISSUE TITLE
wrong album for offline scrobbles

### ISSUE THREAD

**Issue by LouhaneDelforge** [kawaiiDango/pScrobbler#367]
**Describe the bug**
when I scrobble offline, tracks either don't get album at all of wrong ones (the last one registered before going offline)
for exemple today I listened to say so by dojo cat on album hot pink, I then lost connexion (deprived zone I guess?) for 2 songs and well.. my last fm showed murder one by metallica on hot pink (not hardwired...to self-destruct) and feel something by bea miller on hot pink too (instead of quarantine)

**Steps to Reproduce**
tbh I don't know ? I often notice this when the data comes and goes (poor section on the road) rather than a few hours straight (cutting data during a flight for exemple) so..

**App version**
v 3.6 aug 16 2023

**Additional info**
none

**Comment by kawaiiDango** [comment]
Which music player are you using?

**Comment by LouhaneDelforge** [comment]
youtube music ! 
when this doesn't apply, there is simply no mention of album _at all_
![image](https://github.com/kawaiiDango/pScrobbler/assets/70957994/bc5f0082-2465-477b-8f13-f294247951ea)

**Comment by kawaiiDango** [comment]
This is a youtube music bug. Use a different music player

**Comment by LouhaneDelforge** [comment]
> This is a youtube music bug. 
well that's sad to hear
> Use a different music player 
cant really afford another one + some artist that i listen to are not on spotify or anywhere else
