### ISSUE TITLE
Shortcut to Scrobble from mic

### ISSUE THREAD

**Issue by ThreeDeeJay** [kawaiiDango/pScrobbler#369]
**Is your feature request related to a problem, or particular use cases? Please describe.**
Currently, there's no app shortcut to start scrobbling/detecting audio from mic using ACRCloud.

**Describe the solution you'd like**
It would be nice to have an app shortcut that can be added to the home screen, or as an intent like the other ones that were added for Tasker, or even just an activity so we can add the shortcut via Xposed Edge.

**Additional info**

**Comment by kawaiiDango** [comment]
There is one
![markup_1000003786.png](https://github.com/kawaiiDango/pScrobbler/assets/1066519/4536091e-fc6e-4f7c-ab4e-df3ae366e979)

**Comment by ThreeDeeJay** [comment]
What the- I thought those were the same as app shortcuts, but there were none for PanoScrobbler or Custom Notifications app, just the widget. 🤔 
Guess this'll do for now, thanks mate! 👍
