### ISSUE TITLE
Is it possible for the app to remember metadata edits/corrections made to tracks scrobbled from YouTube? 

### ISSUE THREAD

**Issue by NomaanMalick** [kawaiiDango/pScrobbler#37]
When I am watching music videos on YouTube with unconventional or non-romanized titles, the app either scrobbles incorrectly or fails to recognise tracks. The solution is to manually enter the metadata each time I watch a music video which is really a minor hassle if it is an English language song, but the complications arise with non-English songs with romanized or even worse non-Latin script titles. Sometimes when I replay such music videos, I am frustrated by the need to re-enter the metadata on each play. I wish there was a mechanism that allowed the app to store corrections and automatically scrobble them the next time the same music video is played.

**Comment by kawaiiDango** [comment]
edits will now be remembered
