### ISSUE TITLE
wearOS support

### ISSUE THREAD

**Issue by mavproductions** [kawaiiDango/pScrobbler#373]
**Is your feature request related to a problem, or particular use cases? Please describe.**
I would love to have the ability to scrobble from my watch when I'm out for runs/bike rides and I leave my phone at home. I generally use spotify or navmusic, but only spotify can natively scrobble, but it tends to be either delayed, or inaccurate with scrobbles. Pano would help fix this greatly I think, not to mention, I would love to be able to use other music apps on my watch and not have to feel tied to Spotify Premium for offline downloads/playback.

**Describe the solution you'd like**
Some sort of companion app would be really nice that could log offline scrobbles like panoscobbler does, then push to last.fm once back home and wifi-connected or bluetooth paired with phone.

**Additional info**
♥

**Comment by kawaiiDango** [comment]
I have never owned a wearOS device but according to [this](https://stackoverflow.com/questions/76105978/find-currently-playing-song-on-wear-os), it is not possible.
