### ISSUE TITLE
Feature Request: Send album artist data to last.fm right away.

### ISSUE THREAD

**Issue by metronightly** [kawaiiDango/pScrobbler#374]
Currently pano scrobbler doesn't send album artist data right away to last.fm which causes last.fm to wrongfully create albums with the track artist as album artist.

While we can edit album artist for such mishaps later in pano scrobbler, it would be really awesome if the albumartist data is sent before right away to save time and effort for users.

**Comment by kawaiiDango** [comment]
#227

**Comment by kawaiiDango** [comment]
I personally use Poweramp
