### ISSUE TITLE
"No such artist" on artist names with commas.

### ISSUE THREAD

**Issue by HZRDOUS** [kawaiiDango/pScrobbler#38]
Scrobbling with TIDAL, and with artists on that app, featured artists are seperated with commas in between artists. (e.g. "Pierre Bourne, Young Nudy, Lil Uzi Vert"). The app doesn't seem to like this type much. Every time I try to scrobble a track with formatting like that it tells me "no such artist", even though it's in the last.fm database.

**Comment by kawaiiDango** [comment]
You can now add exceptions for unrecognised artists from the notification
