### ISSUE TITLE
Advanced scrobbling settings

### ISSUE THREAD

**Issue by Ede123** [kawaiiDango/pScrobbler#39]
I just switched from Simple Last.fm scrobbler (as it's broken for my Sony music app and seems inactive) and really like Pano Scrobbler in comparison.

One area in which Pano Scrobbler could improve, though, is advanced scrobble settings, where SLS has some advantages (see screenshot below).

Specifically it allows to configure in detail when and what to scrobble (including "Now playing") and has different settings for battery operation in contrast to plugged-in operation (many of these are supposed to reduce battery usage and reduce network overhead).

Do you think some of those would make sense to implement into Pano Scrobbler as well?

---
![Screenshot_20190516-191240b](https://user-images.githubusercontent.com/904570/57873889-a7688c00-780f-11e9-8555-02d1318b4e46.png)

**Comment by kawaiiDango** [comment]
I don't think those options would conserve any real battery, considering that pano scrobbler runs as a notification listener in the background all the time even when not in use. They do conserve a few KBs of data, but I'd rather have background data turned off if I'm on a data budget

**Comment by Ede123** [comment]
I have to admit I was never sure if this made a real-world difference. What I could imagine is that waking the transmitter to send the data every few minutes wastes a few mWh, though. Sending in batches would avoid that.

At the very least least the switch to disable "Now playing" seems reasonable, though, as I suspect most users only care about the actual scrobble and couldn't care less about notifying last.fm ahead of time. (I only ever find it useful while checking if a scrobbler works at all)
