### ISSUE TITLE
inability to scrobble "album artist" 

### ISSUE THREAD

**Issue by greenscarf07** [kawaiiDango/pScrobbler#41]
it seems when there is a different "artist" from the "album artist" on a track when said track is scrobbled panoscrobbler only picks up, Song, Artist and Album. Last.fm then seems to assume that album artist must be the same as the artist. This is not always the case though - for e.g. film soundtracks usually have the album artist tag of "Various Artists", while individual tracks have the "artist" set to who wrote the specific track. In this scenario you would get 7 or 8 or how many different "artist" tags set on individual tracks worth of different albums stored. The "Pulp Fiction Soundtrack" is a good example of this because while having the album artist tag as "Various Artists" there are many different artists for each specific track. So if I were to scrobble this album on my phone (using panoscrobbler) and I were go to check my last.fm later i would have around 7 or 8 different logged albums instead of just one logged album. E.g. one album logged 

"Album: Pulp Fiction Soundtrack"
"Song: Misirlou"
"Artist: Dick Dale"
"Album Artist: Dick Dale"

another one logged

"Album: Pulp Fiction Soundtrack"
"Song: Son of a Preacher Man"
"Artist: Dusty Springfield"
"Album Artist: Dusty Springfield"

etc. etc.

where it should be:

"Album: Pulp Fiction Soundtrack"
"Song: Misirlou"
"Artist: Dick Dale"
"Album Artist: Various Artists"

etc. etc.

there would definitely be other scenarios where album artist would be different to artist but this seems to be the most common one that comes to mind.

this doesn't seem to be an issue at all on PC (and mac i guess as well?) but I don't know of any android scrobbler that doesn't have this issue but panoscrobbler is my favourite scrobbler and this is basically my only issue with it that i can see now - so it would be great to see some sort of solution to this

**Comment by kawaiiDango** [comment]
https://github.com/kawaiiDango/pScrobbler/issues/35#issuecomment-486937210 use a different player
