### ISSUE TITLE
A few artists don't get scrobbled from some apps

### ISSUE THREAD

**Issue by Strannikus** [kawaiiDango/pScrobbler#42]
A few artists don't get scrobbled from AIMP (same tracks from foobar2000 and even Telegram — OK).
Error is  Last.fm: ignored `%artistname%`

**i.g.**: https://www.last.fm/ru/music/Tsuyoshi+Yamamoto and the whole Album ([this one](https://www.discogs.com/Various-The-Super-Extended-Resolution-Sound-Of-TBM/release/4779481))
Official last.fm app shows that scrobbling going on, but it does not save actually. Maybe because of `.opus `file?

Artyom of AIMP said from app side everything goes fine (even with the same file).

 ![Screenshot_20190722-225321](https://user-images.githubusercontent.com/26332718/61662368-f7b00e80-acd6-11e9-911b-b42df3fadd89.png)

Both fresh pScrobbler & AIMP.

**Comment by kawaiiDango** [comment]
That error is from lastfm. Most scrobblers don't notify about the error, pano does.

**Comment by Strannikus** [comment]
Oh, please. Ok, but what is wrong with this album? Why does last.fm ignored it but others?
It's ok from mobile / PC fb2k — what difference between AIMP and fb2k scrobbles?

**Comment by kawaiiDango** [comment]
There is no documentation on lastfm about why some songs get ignored. Maybe ask in lastfm support. Also there was a recent crackdown on artists with hate speech, not sure if it is related to that.

**Comment by Strannikus** [comment]
If Pano sends the same info to lastfm (bit-to-bit, right?) from any supported app, why does only AIMP get this issue with those files, exact this album?

![2019-07-22 23-25-53_git](https://user-images.githubusercontent.com/26332718/62006271-20a52900-b147-11e9-99ea-c2f08338e0da.PNG)

A few updates of Pano before there was the same problem even for Ella Fitzgerald, I believe it was not connected with hate speech :)
