### ISSUE TITLE
Single "force scrobble" Toggle

### ISSUE THREAD

**Issue by Cak3lies** [kawaiiDango/pScrobbler#43]
Not too long ago I realized some of my tracks didn't seem to be scrobbling, and after digging this may be the reason. It's similar in nature to #40, but the solution here doesn't apply to users who disable the notification (that includes me). So I am wondering if a toggle setting could be created. 

Not only does it help for the above situation, but it would also lessen the hassle of adding exceptions for tracks like so:
![Screenshot_2019-08-06-16-12-55~01](https://user-images.githubusercontent.com/16861429/62523841-27f1c400-b824-11e9-9444-87eea3784f7d.png)

Considering also that Lastfm now has a edit feature (albeit for paying users :v) and that foobar scrobbling plugins have a similar option, I feel like a universal toggle won't hurt. Anyways, thanks for your hard work! 

(also nice tastes, I happen to listen to Doujin/Bemani stuff too)

**Comment by kawaiiDango** [comment]
Don't want to pollute lastfm's database with names of radio stations and personal Chromecast devices
