### ISSUE TITLE
App crashes/quits when uploading audio from "scrobbling from mic" feature

### ISSUE THREAD

**Issue by KatyLB** [kawaiiDango/pScrobbler#44]
Reported by several people on the Last.fm Reddit, so it's not just me. (https://www.reddit.com/r/lastfm/comments/cxtk3o/pano_scrobbler_update_scrobble_from_mic/)

The application crashes when it gets to the "Uploading..." stage of the new "scrobbling with mic" feature. It does this every time. It listens for the audio fine, but crashes when uploading it.

My own device is a Samsung Galaxy S8 Plus.

**Comment by kawaiiDango** [comment]
Need logs. Send a bug report. Also, does it happen every time?

**Comment by KatyLB** [comment]
I've just sent a feedback bug report now with the logs. Yes, it happens every time.

**Comment by kawaiiDango** [comment]
I didn't get any mail. Did you select but report from the menu?

**Comment by KatyLB** [comment]
I've sent it that way now.
