### ISSUE TITLE
Regulary scrobble my last Spotify free listening

### ISSUE THREAD

**Issue by Fabe56** [kawaiiDango/pScrobbler#45]
Even if Pano isn't configured to scrobble Spotify, the Android app still regularly scrobbles the same last song I listened to Spotify. As I stop using Spotify (for the moment), I uninstall the app but it looks like I'm not alone with [this issue](https://community.metabrainz.org/t/weird-listenbrainz-issue-constantly-submitting-wrong-listen-the-division-2-ost/431528/3?u=fabe56).

**Comment by kawaiiDango** [comment]
Send a bug report from the app shortly after this happens. Also, do you see pano scrobbler notification when it is scrobbling?

**Comment by kawaiiDango** [comment]
No bug report received. Closing
