### ISSUE TITLE
Allow application to work without notification access

### ISSUE THREAD

**Issue by theHilikus** [kawaiiDango/pScrobbler#46]
Notification reading should not be mandatory.
If I want to only scrobble from an app, it should be valid to skip the step to "grant notification access" to the app. I actually gave it access just to be able to configure the app, went to the settings and configured only poweramp and even disabled scrobbling from notifications. the next time i opened the app, it wen't back to the "Almost there..." screen and nothing is scrobbled anymore

**Comment by kawaiiDango** [comment]
Notification access is mandatory to receive music metadata
