### ISSUE TITLE
can no longer authenticate on chromebook.

### ISSUE THREAD

**Issue by rickdog** [kawaiiDango/pScrobbler#47]
stopped scobbling, so I logged out/in in app, but it won't authenticate.  see screenshot.
![Screenshot 2019-09-15 at 4 57 31 AM](https://user-images.githubusercontent.com/77186/64919993-c2c0b500-d777-11e9-8527-b989153baf19.png)

**Comment by rickdog** [comment]
I unistalled/reinstalled, same issue.

chrome: Version 77.0.3865.77 (Official Build) beta (64-bit)

**Comment by rickdog** [comment]
This also applies to Pano on my Android devices.  I can't even authenticate in Tidal, so is either a Last.fm login problem or they changed they way they do it.

**Comment by x1sun** [comment]
having the same issue here, hope i don't lose the data 😢

**Comment by kawaiiDango** [comment]
Everyone is having the same issue https://www.reddit.com/r/lastfm/comments/d4eaye/my_lastfm_app_got_logged_out_unexpectedly_and_now

**Comment by kawaiiDango** [comment]
Some people reported it to be fixed by now
