### ISSUE TITLE
[Feature Request] Android TV

### ISSUE THREAD

**Issue by stuaxo** [kawaiiDango/pScrobbler#48]
Hi,
   I use Youtube on my Android TV a lot and having PanoScrobble would be good there.

Cheers
Stuart

**Comment by kawaiiDango** [comment]
Not possible

**Comment by kawaiiDango** [comment]
https://stackoverflow.com/questions/48855434/enable-notification-access-using-adb
Its actually possible if you enable usb debugging and type 
`adb shell cmd notification allow_listener com.arn.scrobble/com.arn.scrobble.NLService`
and repopen the app.
Havent tested youtube scrobbling on a tv. try it out and let me know

**Comment by stuaxo** [comment]
What's the best way of getting the adb so I can try sideloading it?
