### ISSUE TITLE
Some scrobbles from YT Music will record the previously listened track's album

### ISSUE THREAD

**Issue by Turbotailz** [kawaiiDango/pScrobbler#49]
I've just noticed today, after looking through my scrobble history over the past few weeks, that a lot of my scrobbles from YouTube Music have been messed up where the tracks have been recorded with the previously listened track's album name.

The track name and artist name seem to be recorded right, but the album is wrong in many cases.

If you want to see an example, here is a link to page 5 of my scrobbles which shows a lot of these errors: https://www.last.fm/user/turbotailz/library?page=5
You can hover over the blank album covers and you'll see they show the correct artist name, but the album name of the track before it.

I'm not sure when this started, I'm still going through my scrobble history to find out. Not looking forward to having to fix these :( hopefully you can find a fix.

**Comment by ChelohHolmes** [comment]
I realized this a while ago too. After using YT Music for a while, I have to edit the scrobbles, it's a bummer.
But I think this is an issue with YT Music itself and not Pano Scrobbler, maybe the app takes some time to change albums or something.
But maybe we could fix it by waiting a little before getting the data for the scrobble.

Meanwhile, you can fix it by pausing the track a second and resuming it after, it works fine that way.

**Comment by Turbotailz** [comment]
Thanks for the tip. In the meantime I have switched back to Google Play Music which works flawlessly as always.

**Comment by kawaiiDango** [comment]
Just gathered that this also happens with Simple Scrobbler and Scroball, so there's something wrong with YouTube music itself

**Comment by hotmule** [comment]
I had no problems with Scroball, everything always worked properly, on Android 8-10, with different devices

**Comment by kawaiiDango** [comment]
Check the update (1.88), I fixed a derp

**Comment by hotmule** [comment]
Thank you Kawaii, very cool!

**Comment by Turbotailz** [comment]
That seems to have fixed it, thank you!
