### ISSUE TITLE
Emergent artists' tracks don't get scrobbled even if they actually exist and are scrobbled by official Last.fm app

### ISSUE THREAD

**Issue by AryToNeX** [kawaiiDango/pScrobbler#5]
The title says it all. I tried scrobbling an emergent alternative rock band called 'Hypergear' but Pano says 'No such artist' when the official Last.fm app scrobbles their tracks just fine.

https://www.last.fm/music/Hypergear

**Comment by fimzoak** [comment]
I've seen the same issue with https://www.last.fm/music/KYRIE+00000.

**Comment by kawaiiDango** [comment]
You can now add exceptions for unrecognised artists from the notification
