### ISSUE TITLE
Separate Artist field from Album artist field

### ISSUE THREAD

**Issue by whoozwah** [kawaiiDango/pScrobbler#52]
when scrobbling from gonemad music player on tracks where the artist field and album artist field are different, pano is scrobbling the artist field AS the album artist field instead of scrobbling them as different fields. This results in incorrect scrobble data. Requesting that pano respect the file metadata and scrobble them as they are and separate album artist and artist fields.

Thanks.

**Comment by kawaiiDango** [comment]
Pano Scrobbler supports album artists. Disable Broadcast Metadata in
general settings in gonemad player to prevent conflicts.

**Comment by whoozwah** [comment]
ok. I've disabled Broadcast metadata. Will test. Thanks.

**Comment by kawaiiDango** [comment]
Seems to work fine here
