### ISSUE TITLE
[Feature request] Scrobble from Google's "Now Playing" status

### ISSUE THREAD

**Issue by qyZMVYcw1VA6** [kawaiiDango/pScrobbler#55]
I was recently gifted a Pixel 3a. It has a feature where it detects music playing around you automatically with no interaction necessary. I tried to find this "Now Playing" notification thru Pano's application browser though it didn't show up.

The tracks are formatted in notification bar as:
(line 1): "Rape Me by Nirvana
(line 2) Tap to ask your Assistant about this song"

The Now Playing notification appears to be from the "Pixel Ambient Services" app, which I also couldn't find on Pano's application browser.

See:

![Screenshot_20191230-124052](https://user-images.githubusercontent.com/47117778/71593356-addb1800-2b01-11ea-95c0-c7f91e40b810.png)
![Screenshot_20191230-124134](https://user-images.githubusercontent.com/47117778/71593374-c0ede800-2b01-11ea-9b64-7d975d83bbca.png)

**Comment by lindner** [comment]
There's another app that does this named "Now Playing".  I'd rather this functionality was in a single app, so yes would love this feature..

**Comment by kawaiiDango** [comment]
@lindner does it scrobble?

**Comment by Dtrieb** [comment]
> There's another app that does this named "Now Playing". I'd rather this functionality was in a single app, so yes would love this feature..

Could you please give a Link?

**Comment by pythonInRelay** [comment]
> > There's another app that does this named "Now Playing". I'd rather this functionality was in a single app, so yes would love this feature..
> 
> Could you please give a Link?

Have you tried literally just checking the Play Store for the app name he mentioned?

**Comment by lindner** [comment]
> > > There's another app that does this named "Now Playing". I'd rather this functionality was in a single app, so yes would love this feature..
> > 
> > 
> > Could you please give a Link?
> 
> Have you tried literally just checking the Play Store for the app name he mentioned?

I checked and there are multiple Apps that provide this feature.  I went with this one:

https://play.google.com/store/apps/details?id=com.greatbytes.nowplayinghistory

> > @lindner does it scrobble?
> 
> No it doesn't. All the service does is keep your microphone in use 24/7 so it can identify any music in your vicinity. That's added to a list which is stored on the device.

The linked app does indeed listen for notification changes, parses the Pixel's song information, stores it locally and Scrobbles it to Last.fm.

**Comment by kawaiiDango** [comment]
Pixel's now playing is now considered as regular scrobbles, so scrobble delay and cancellation applies. It uses 2/3rd of whatever is set in "scrobble delay in secs" because the default is 4 mins and some songs aren't even that long
