### ISSUE TITLE
[Features Request] debug NicoBox

### ISSUE THREAD

**Issue by ManshionProd** [kawaiiDango/pScrobbler#56]
Actually the scrobble do not applied the good artist/uploader tag (instead, the scrobble tags the url, more precisely the sm...). 
so you should either make an exception for the application (since if I'm not mistaken the name of the uploader is in the metadata) or have the possibility to modify how the scrobble read the metadata , according to the apps.

**Comment by kawaiiDango** [comment]
Support will be added. Do you know any other similar apps which should be supported?
