### ISSUE TITLE
Don't scrobble tracks shorter than 30 seconds

### ISSUE THREAD

**Issue by cekc** [kawaiiDango/pScrobbler#58]
I'm using Pano Scrobbler v1.63, Android 8.0.0. Scrobbling mostly from Google Play Music app.

Currently, Pano Scrobbler does scrobble tracks shorter than 30 seconds.

[Official API documentation says:](
https://www.last.fm/api/scrobbling#when-is-a-scrobble-a-scrobble)
> A track should only be scrobbled when the following conditions have been met:
> 
> + The track must be longer than 30 seconds.
> + And the track has been played for at least half its duration, or for 4 minutes (whichever occurs earlier.)

Short tracks (those for which we can get length from metadata or some other source) shouldn't be scrobbled. Or, at least, there should be an option in the app to toggle that.

**Comment by kawaiiDango** [comment]
I have some legit songs which are less than 30 secs in my library and they should be scrobbled:

Linkin Park - Riff raff (22s)
Linkin Park - Chali (23s)
すみじゅん - Tonic Triangle (24s)
daoko - 向こう側の女の子 (25s)

And more
