### ISSUE TITLE
scrobble from mic doesn't work anymore

### ISSUE THREAD

**Issue by sheb667** [kawaiiDango/pScrobbler#59]
Since a few minutes I can't scrobble from mic anymore.
It says: "limit exceeded, please upgrade your account"
Which account ?

By the way ACRCloud's service is not very good. A lot of "no result" or even wrong results.

**Comment by Dtrieb** [comment]
+1

**Comment by pythonInRelay** [comment]
Yeah it hasn't worked for a while. Keeps whining that I've used my free limit. I guess the developer has raked in too many API calls. Btw guys, this app doesn't seem to be under development any more. I'm looking at forking it and seeing if I can iron out some issues.

**Comment by kawaiiDango** [comment]
This project is very much in active development lol. You will be able to add your own ACRCloud keys in the upcoming version, but I'm fixing some bugs now. https://imgur.com/qEgiohN 
Also, I know that their api isnt very good, but it is the only free one that I know of. Gracenote used to be another one, but since last year, they are no longer allowing free signups

**Comment by pythonInRelay** [comment]
Great news mate. Just out of curiosity, did you remove some kind of feature that only scrobbled videos on Youtube/NewPipe that were tagged under "Music" category? I can't find it any more. I swear it used to be there and it stopped a lot of instant scrobbles of just regular videos.

If there's anything you want help with in particular, let me know.

**Comment by kawaiiDango** [comment]
There was no such feature, because you can't detect if they fall under the Music category just from the video title and channel name. Browser extensions can do it because they have access to the entire content on the page.

**Comment by pythonInRelay** [comment]
Roger that,  

> Browser extensions can do it because they have access to the entire content on the page.

That's where I got confused. Thanks for the clarification.

**Comment by kawaiiDango** [comment]
> 
> 
> This project is very much in active development lol. You will be able to add your own ACRCloud keys in the upcoming version, but I'm fixing some bugs now. https://imgur.com/qEgiohN
> Also, I know that their api isnt very good, but it is the only free one that I know of. Gracenote used to be another one, but since last year, they are no longer allowing free signups

its up

**Comment by pythonInRelay** [comment]
Took about 5 minutes. Seems to be working flawlessly now. Thanks a lot man! You got a donation link?

**Comment by kawaiiDango** [comment]
Check if this works http://bit.ly/donateBot

**Comment by sheb667** [comment]
problem is already back :(

**Comment by kawaiiDango** [comment]
It should be. Its not possible to serve the growing number of users with my free account. Just add your own account from the 3 dots menu

**Comment by sheb667** [comment]
ok, got it now ! It works. Thx for the answer and the nice app. I was looking for a mic scrobbling app for months...

**Comment by Dtrieb** [comment]
> It should be. Its not possible to serve the growing number of users with my free account. Just add your own account from the 3 dots menu

Can you make the link to the website clickable?

**Comment by kawaiiDango** [comment]
will do
