### ISSUE TITLE
Skipping scrobbles.

### ISSUE THREAD

**Issue by MaiconErick** [kawaiiDango/pScrobbler#60]
Didn't test on other players. On musicolet when you delete a song that is playing, the next song won't scrobble, the pani notification won't even appear unless you seek through the song, fast forward or jump to the next song. I also tried all three notification styles of Musicolet.
It also happens sometimes even if you don't delete anything, but I couldn't track down why.

**Comment by kawaiiDango** [comment]
That seems to be an issue with the player
