### ISSUE TITLE
[Feature Request] Manual Scrobble Queue Option

### ISSUE THREAD

**Issue by pythonInRelay** [kawaiiDango/pScrobbler#61]
Would this be possible? I'd like an option to queue up scrobbles of things I've listened to and then manually submit them after a period of time. So for example if my last play list was something like:

[ Song - Artist ] ✔️
[ Song - Artist ] ✔️
[ Video - Artist ] ❌
[ Song - Artist ] ✔️
[ Song - Artist ] ✔️
[ Video - Artist ] ❌

I could mark ❌ or ✔️ beside things I actually want scrobbled instead of having to delete unrelated videos/etc. via the app (which doesn't work sometimes) or Last.fm (which is really cumbersome) that have been scrobbled automatically.

Could this be possible with a cache option of some sort? I would absolutely pay for a feature like this.

**Comment by kawaiiDango** [comment]
Nope, I don't want to clone this from Simple Scrobbler. I personally use the undo button in the notification if an unrelated video scrobbles, and the delete option.

**Comment by pythonInRelay** [comment]
Fair enough then. The problem with using undo is that if I don't make it in time the only option left is delete which doesn't always work. I'll close the request though. Hopefully you can consider this in the future if you get bored. You don't have to clone it from another app.

Peace.
