### ISSUE TITLE
Scrobble fields mixed up from Triple J Android app

### ISSUE THREAD

**Issue by orerocks** [kawaiiDango/pScrobbler#62]
Pano picks up the scrobble fields from the Triple J Android app, but puts them in the wrong order.

Track shows the channel
Album is correct
Artist shows the track name and artist

First image shows the Pano edit fields option. The second shows the son info in the Triple J app. 
![Screenshot_20200215-095745](https://user-images.githubusercontent.com/31866231/74592884-84574c80-4fda-11ea-999c-2ae897edb255.png)
![Screenshot_20200215-095804](https://user-images.githubusercontent.com/31866231/74592885-8b7e5a80-4fda-11ea-9d5d-b4493250b7f2.png)

**Comment by orerocks** [comment]
Furthermore, even if I edit the fields in Pano, the app reports 'No such artist' even for well known artists and songs.

**Comment by kawaiiDango** [comment]
Pano doesn't put fields in the wrong order, your player does.

Also the artist not found error is actually a rate limit error from lastfm on my API key. Check whether it also happens in the latest update

**Comment by orerocks** [comment]
The editing is fixed. I have sent a help request to the other dev.
