### ISSUE TITLE
Reorder tag infos

### ISSUE THREAD

**Issue by sheb667** [kawaiiDango/pScrobbler#63]
I Use pano scrobbler with Accuradio app but I have to scrobble it from mic cause infos given are not in the right order.
Instead of having "Title - Artist" it gives me "Title - Album" so scrobbling is wrong.
I was wondering if the order could be corrected, even manually then the app knows that when scrobble comes from this specicfic app, this reorder of the infos must be used ? 

Would be really very useful... at least for me :-)
It will also avoid the wrong recognition (last one I had: a DJ instead of AC/DC !)
thx

**Comment by 4rion** [comment]
Hi, 

To begin with, a big **thank you** for Panoscrobbler! :)
I have much the same problem with the Radio France app : **artist and title tags are swapped**.

We should be able to save the artist / title swap for this or that app.

I imagine a long press on the swap button (in the edit box) which means "lock the swap for this app".

What do you think about that ?

**Comment by kawaiiDango** [comment]
#152
