### ISSUE TITLE
Edit album artist?

### ISSUE THREAD

**Issue by j95854** [kawaiiDango/pScrobbler#64]
Is there a way to edit and/or keep the data in the album artist field? For example, if I'm editing the artist on a track from a compilation, I can prevent it from adding a separate album by that artist?

**Comment by j95854** [comment]
Is an editable album artist field a feature that will ever be added?

**Comment by kawaiiDango** [comment]
There's no way to retrieve the existing album artist from a past scrobble using the API, so a box to edit album artist will always be blank. This will not be "true editing". This will lead people to think that the scrobbler doesn't scrobble album artists or doesn't save the album artist when edited and there already have been many people claiming that this scrobbler doesn't support album artists on GitHub issues, Reddit and my mail, when it is just their player's fault.
