### ISSUE TITLE
Add support for YMusic

### ISSUE THREAD

**Issue by MalikKillian** [kawaiiDango/pScrobbler#65]
Adding YMusic as an "Other" app for music usually doesn't work.  pScrobbler will pick up the channel name as the artist when YMusic plays.  It should be added to the list of apps that ignores the "artist metadata" field in notifications.

The package name for the version I have is "com.kapp.youtube.final".  I don't know if there are any variations to this.

**Comment by kawaiiDango** [comment]
Will add

**Comment by sheb667** [comment]
Same thing goes for Accuradio (see #63)

**Comment by kawaiiDango** [comment]
> 
> 
> Same thing goes for Accuradio (see #63)

No thats different
