### ISSUE TITLE
Feature request: routine to delete duplicate scrobbles 

### ISSUE THREAD

**Issue by dgr7** [kawaiiDango/pScrobbler#66]
Hi
Please create a routine that a user could run with one click where it would go through past recent scrobbles and delete any duplicate scrobbles based on   if the timestamp is the same along with the artist and title.  Right now I have to manually delete each duplicate.  It would be greatly appreciated!   
Thanks.

**Comment by kawaiiDango** [comment]
This will spam the lastfm api and could get my app banned. How are you getting duplicate scrobbles anyways?
