### ISSUE TITLE
About SoundCloud scrobbles

### ISSUE THREAD

**Issue by awsms** [kawaiiDango/pScrobbler#67]
Hi kawaiiDango, first of all thanks for this great app.
I think soundcloud tracks should be scrobbled using the same format used for scrobbling on YouTube.
Since most (99.9%) of soundcloud tracks use the format "%artist% - %track%" ; it should be also the same way as YouTube is scrobbled (using the name of the video instead the name of the YT channel).
And for the tracks that do not contain a `-`, the artist tag would be the actual artist name

**Comment by awsms** [comment]
![Screenshot from 2020-04-01 09-44-09](https://user-images.githubusercontent.com/48278661/78111836-927ff180-73fd-11ea-94f6-005eb7e9d254.png)

That's the kind of messy stuff I'm talking about in the original post

**Comment by kawaiiDango** [comment]
Implemented
