### ISSUE TITLE
Nicobox issue

### ISSUE THREAD

**Issue by KiyaSiph** [kawaiiDango/pScrobbler#68]
Hi! I've been scrobbling from the app "Nicobox" (a Niconico douga player) for a while and never had any problems, but after the last update(s? Honestly haven't updated for a few months, so I don't know which versions I was using until now @_@) it won't let me automatically scrobble most of the songs I listen to (the "Couldn't parse title (Tap to edit)" error pops up, and while it does scrobble if I edit it in the notification menu, it won't remember it the next time, so the error just keeps popping up anytime I listen to them and I have to manually fill in the blanks ;_;) 
I noticed that what all these songs have in common is that when I tap to edit the entry, the "Track" field is empty (as in the attachment). 
Is this fixable? ;__; having to manually edit everything everytime it's kinda bothersome;; 
Anyway, thank you so much for this app and for your time! 
![photo_2020-04-14_03-28-34](https://user-images.githubusercontent.com/63622870/79176284-1a073080-7e00-11ea-91d9-14a12fe9fb94.jpg)

**Comment by kawaiiDango** [comment]
As of now, the title needs to be in artist - title, or similar formats for the parser to work. There doesn't seem to be any standard title format for Japanese videos. I'll check what changed after the update.

Edit and remember seems to work fine here. Can you provide some links to videos where editing isn't remembered?

**Comment by KiyaSiph** [comment]
Thanks for answering! Yup, here! 
https://www.nicovideo.jp/watch/sm21933214 (and all of his videos as far as I've seen)
https://www.nicovideo.jp/watch/sm34915842
I tried to fix this rebooting my phone, unistalling and installing again both Nicobox and Pano and using different names while editing, but as of now it still won't let me edit these songs. 
It does work with many other other songs if the app can automatically put something in the track field (even just a letter or a symbol), though!

**Comment by kawaiiDango** [comment]
Should be fixed in the latest update. Play store says "Due to adjusted work schedules at this time, we are currently experiencing longer than usual review times. Please expect review times of seven days or longer."
