### ISSUE TITLE
Cannot get past "Grant notification access"

### ISSUE THREAD

**Issue by jjech** [kawaiiDango/pScrobbler#70]
Is there a way to bypass notification access, or is it required for PanoScrobbler to read metadata even with simple audio apps such as Poweramp?

I am using a FiiO M6 DAP, which runs a stripped down version of Android 7.0. When I launch PanoScrobbler, I can successfully complete steps 2 and 3, but get stuck on step 1 (Grant notification access).

When I tap to enable notification access, PanoScrobbler gives me the instructions for ADB, but I'm not sure if I can enable developer options on this highly customized version of Android (tapping the build number turns on the ability to install third party apps [normally these have to be whitelisted], rather than enabling the traditional developer options).

It would be ideal if I could bypass this, but if it's required to read metadata then I might be SOL (at least as far as PanoScrobbler goes).

**Comment by jjech** [comment]
I was able to enable developer options by tapping the build number --- enabling third party install was enabled by tapping on kernel version, not build number. Should be able to get things going now.

**Comment by jjech** [comment]
It's working! Thanks for the excellent documentation on granting notification access for older versions of Android.

**Comment by downlow79** [comment]
I seem to be having a similar issue as above. 

I get a "Connection refused" message when running the "adb connect  <ip address>" command in terminal.

I am following these instructions: https://telegra.ph/Pano-Scrobbler-on-TV-11-21.

Is there other documentation I should be following? I can't find anything.

Thank you
