### ISSUE TITLE
Allow casting of "now playing"

### ISSUE THREAD

**Issue by kstec** [kawaiiDango/pScrobbler#71]
Use chromecast to cast a "now playing" page of the track and/or album. Could display lyrics, ratings, album art, credits.

Possible sources:
* Discogs
* Lastfm
* RateYourMusic
* Genius
* Metal Archives
* Wikipedia

This would be great coupled with Pixel's "Now Playing". You could cast information about songs from FM radio, XM, vinyl, whatever is playing.

**Comment by kstec** [comment]
Like https://www.last.fm/user/{user}/now but with more stuff.

**Comment by jawshoeah** [comment]
This site might be a good source of inspiration. https://descent.live/now

But honestly, just a simple cast of https://www.last.fm/user/{user}/now  would be awesome!

**Comment by kawaiiDango** [comment]
Closing as I will not be implementing this
