### ISSUE TITLE
is not working with Samsung One UI 2.0 on Android 10 (fresh update)

### ISSUE THREAD

**Issue by deathisinevitable** [kawaiiDango/pScrobbler#73]
for me and many users (you can read it on xda)

**Comment by deathisinevitable** [comment]
and send to you 2 weeks ago my logs and screenshot of the app

**Comment by kawaiiDango** [comment]
If you were the one with lastfm ignored message, your player is sending the
file name in place of the song name, which lastfm ignores.

**Comment by deathisinevitable** [comment]
> If you were the one with lastfm ignored message, your player is sending the file name in place of the song name, which lastfm ignores.

thanks to you!
