### ISSUE TITLE
About every other Hype Machine scrobble is missed.

### ISSUE THREAD

**Issue by jaccarmac** [kawaiiDango/pScrobbler#74]
Noticed this while listening to a premiere the other day. It's not quite every other track, but roughly speaking the first track to play will scrobble fine, but the app won't pick up a song until the second track ends and the third begins.

**Comment by kawaiiDango** [comment]
There's a bug report option in the app. Use that, shortly after reproducing the bug.

**Comment by jaccarmac** [comment]
Done. Was even able to see the issue on the first play from Hype Machine. I saw a notification badge for a moment but it disappeared before I could read it. I observed something similar when I first saw the issue, though half the time the notification would stick around and was the unrecognized artist notification (which would let me force the scrobble).
