### ISSUE TITLE
Support for Qub Musique

### ISSUE THREAD

**Issue by franc00018** [kawaiiDango/pScrobbler#75]
[Qub Musique](https://play.google.com/store/apps/details?id=com.numeriq.qub.musique&hl=en_US) is a new music app in Quebec, streaming platform like Spotify. 
I enabled it in the Pano Scrobbler apps. 

![Screenshot_20200610-211854_Pano Scrobbler](https://user-images.githubusercontent.com/5459276/84334382-415c4e80-ab60-11ea-89a9-b670d23f0a67.jpg)

It's not detected by Pano Scrobbler when playing. 
The Qub Musique shows a "now playing" notification on Android with metadata. As you can see there is no Pano Scrobbler notification.

![Screenshot_20200610-211915_Pano Scrobbler](https://user-images.githubusercontent.com/5459276/84334385-41f4e500-ab60-11ea-8696-5bb236902949.jpg)

**Comment by kawaiiDango** [comment]
It doesn't send metadata to the Android system. It doesn't even identify itself as a music player to Android
