### ISSUE TITLE
Feature request: Is it possible to scrobble to wavy.fm?

### ISSUE THREAD

**Issue by Nowena** [kawaiiDango/pScrobbler#76]
I am not sure if you can make the app do it but would be nice to have a way to scrobble from android to wavy.fm.
We can only scrobble from spotify at the moment. 
Will we have to wait for wavy.fm to introduce a way to scrobble from desktop/mobile music players for this app to be able to work that way?

**Comment by kawaiiDango** [comment]
They don't have an api at the moment and they seem to focus only on Spotify
