### ISSUE TITLE
Can't Edit Scrobbles at All

### ISSUE THREAD

**Issue by LunaLanaLuana** [kawaiiDango/pScrobbler#77]
I mainly use the app to edit my scrobbles as I do not have Last.fm Premium. 
But, since around 2 days ago, every time I try to edit a scrobble it just doesn't work, after I input the correct metadata, It loads up and the checkmark appears. However, once I reload the app, it reverts back to what it originally was, Please fix this, thank you!
Also, would it be possible to introduce a feature to search for scrobbles of certain artists and sort them by oldest? It would help me a lot with fixing my tags.

**Comment by kawaiiDango** [comment]
This is normal. You need to wait for about 5-10 minutes for the server to update.
You can't edit a scrobble which is more than a 7 days old or something (lastfm keeps changing the number), so sorting by old is useless in this case

**Comment by LunaLanaLuana** [comment]
I've waited 2 days actually, and the edit still hasn't applied.
I remember being able to edit scrobbles that were around 3 weeks old by scrolling down a lot? Not sure.

**Comment by kawaiiDango** [comment]
That probably means that the server isn't accepting edits, which I have no control over.

**Comment by kawaiiDango** [comment]
Try logging out and logging in just in case
