### ISSUE TITLE
LastFM ignores tracks with "Unknown album/artist" tags

### ISSUE THREAD

**Issue by cirnoftw** [kawaiiDango/pScrobbler#78]
I've noticed that some players (mostly network streaming ones) don't work with Last.fm well, scrobbles and "playing now" statuses just keep getting ignored by Last.fm. After some debugging, I found out that those players tend to send "Unknown album" as track album or "Unknown artist" as album artist, etc., because that's how they get tracks from the network, and that's the reason the tracks are ignored.

Can we add an option to ignore "unknown" tags from adding to params list? They are optional anyway, so there shouldn't be a problem to not add them to the list if they contain "Unknown *" values, probably setting them as null or something. That'd be a great help for scrobbling from network apps.

**Comment by kawaiiDango** [comment]
https://www.last.fm/search?q=unknown shows that there are a lot of artists
and albums with "unknown" in their name. Also "unknown" is an english word.
Players may call it something else in other locales and they would be
ignored by lastfm.

Btw which apps are you talking about?

**Comment by cirnoftw** [comment]
There are artists/albums/songs with "unknown" in their name, but Last.fm is specifically strict about sending tags such as "Unknown artist" or "Unknown album" in the tags, which results in tracks getting ignored from scrobbling. Below are my attempts to send "Now playing" to Last.fm with track album set as correct name, "Unknown album" and null. All other tags are completely same, the only tag changing is the album tag:
<img width="236" src="https://user-images.githubusercontent.com/42409435/85325181-e1589700-b4d3-11ea-96f2-f0ac76996b23.png"> <img width="347" src="https://user-images.githubusercontent.com/42409435/85325425-47ddb500-b4d4-11ea-9530-0dfa4bfa5843.png"><img width="304" src="https://user-images.githubusercontent.com/42409435/85325627-9be89980-b4d4-11ea-98a3-1c3c86de5cda.png">
As I checked, the same thing applies to artist, album artist tags, etc. Last.fm just ignores tags it considers incorrect, even though they're not really important anyway and can be set as null. So I think it'd be a nice option to add something like a checkbox allowing users to avoid sending "Unknown artist/album" to Last.fm. I haven't tried it with other services, but as far as I know, their scrobbling policies aren't that strict, so it may be a Last.fm-only solution.

Also, the app I'm using to debug streaming is Stellio Player with VK plugin, although doesn't really matter, it just uses tags as they come from the network, so the same might be applied to any other app getting "Unknown artist/album" from network tags.

**Comment by kawaiiDango** [comment]
I switched to Arabic and used Stellio player. I got ألبوم غير معروف in
place of unknown album. This is also app specific as they can have
different inconsistent strings in different languages and some send
"unknown", "<unknown album>", "[unknown]" etc. Some like Poweramp just puts
null.

**Comment by kawaiiDango** [comment]
Looks like lastfm doesn't ignore unknown album in other languages. Also there are some actual albums titles "unknown". It will now remove "[unknown]", "unknown album", "[unknown album]". I haven't come across a player which puts unknown artist as they album artist. They usually put null or the track artist in the album artist

**Comment by Yohe-Am** [comment]
Sorry for the necromancy but a recent update of Musicolet player suffers from this. Tracks lacking Album Artist no longer scrobble.

Providing a config to bypass/rege this would help with any possible future incompatibilies as well so I thought it better go raise the issue at PanoScrobbler.

**Comment by Yohe-Am** [comment]
Oh, and should I open an new ticket for this?

**Comment by kawaiiDango** [comment]
@Yohe-Am #212 212 (I think I should edit the title to mention Musicolet)
