### ISSUE TITLE
Inability to scrobble "Album Artist"

### ISSUE THREAD

**Issue by impkid** [kawaiiDango/pScrobbler#79]
Last.fm then seems to assume that album artist must be the same as the artist. This is not always the case though - for soundtracks usually have the album artist tag of "Various Artists", while individual tracks have the "artist" set to who wrote the specific track. In this scenario you would get 7 or 8 or how many different "artist" tags set on individual tracks worth of different albums stored. The "Birds of Prey Soundtrack" is a good example of this because while having the album artist tag as "Various Artists" there are many different artists for each specific track. So if I were to scrobble this album on my phone (using panoscrobbler) and I were go to check my last.fm later i would have around 7 or 8 different logged albums with the name Birds of Prey Soundtrack instead of just one logged album. I've already tried Apple Music and Spotify and neither of them worked.

**Comment by kawaiiDango** [comment]
Pano Scrobbler scrobbles album artists if your player allows them to be scrobbled

**Comment by impkid** [comment]
> Pano Scrobbler scrobbles album artists if your player allows them to be scrobbled

So there's no way i can fix it? Oh...

**Comment by kawaiiDango** [comment]
You can use a player which allows album artists to be scrobbled.

**Comment by impkid** [comment]
Which players allows album artists to be scrobbled? I need one immediatly. I've already tried 4 players (Spotify, Apple Music, Tidal and Deezer).

**Comment by kawaiiDango** [comment]
I don't use streaming services much so I don't know about them. I tested on Poweramp and Stellio player and it works
