### ISSUE TITLE
Pending scrobbles (still) won't scrobble

### ISSUE THREAD

**Issue by GlitchWalker** [kawaiiDango/pScrobbler#8]
Hi there, I noticed the issue had been closed regarding pending scrobbles not being sent. As of the 19 Sep update, this problem is still happening for me.

For some reason, the app decides it can't scrobble so puts my new scrobbles in the pending list. This usually happens when I start listening to music again after a break. Force closing Pano Scrobbler and opening it again seems to solve the scrobble issue, however I am still left with a list of pending scrobbles.

I notice in the reply to the previous issue with a similar title, it is mentioned there is an option for foreground scrobbling for pending scrobbles, however I can't find this anywhere in the UI.

**Comment by kawaiiDango** [comment]
Which device/ROM r u on?

**Comment by GlitchWalker** [comment]
I am using the OnePlus 3T, running Android 8.0.0 (the last official version released for this device). I'm just about to send you a bug report from the app, I'll add the title of this issue to the "how did this happen?" section. 

Also thanks for the quick reply

**Comment by kawaiiDango** [comment]
The "advanced optimisation" in oxygen os might prevent jobs to be run in the background. Make sure you have it disabled or ignore battery optimisations if you have it enabled.

About the foreground service, you should get a notification as soon as you open the app, if you have pending scrobbles. Do you get that?

**Comment by kawaiiDango** [comment]
Thanks for the log. It's failing with some XML exception. Will look into that

**Comment by kawaiiDango** [comment]
Does this still happen?

**Comment by Botanistt** [comment]
The same thing happens to me on OnePlus 6T, though I never had an issue on OnePlus 3. I'll try to disable the battery optimisation for the app and I'll let you know if that worked.

**Comment by Botanistt** [comment]
Tested for over a week and haven't had an issue ever since.

**Comment by Darth4212** [comment]
The same thing is happening to me on my LG Stylo 2 running Android 7.0, I am currently at 1158 pending scrobbles

**Comment by DavidVI18** [comment]
I'm having this problem too. On a Samsung galaxy s8.
There's been a few pending scrobbles for a week.
I'd just like them gone, so maybe a fix for now would be the ability to delete pending scrobbles?

**Comment by aisbergde** [comment]
Same pending scobles issue for me. OnePlus 5. It started fine when I was connected only to lastfm. Then I added logins for librefm and listenbrainz. These pending scobles are not transfered to lastfm nor to listenbrainz, but they are visible on librefm. I will try to send a bug report from inside the app.

**Comment by kawaiiDango** [comment]
This should be fixed by now

**Comment by WanHaes** [comment]
Disabling battery optimization for the app have fixed my "stucked" scrobbles instantly. I guess you should add a notification about this setting.

**Comment by kawaiiDango** [comment]
Which device is that?

**Comment by WanHaes** [comment]
Asus ZenFone Max Pro M1, Android P

**Comment by kawaiiDango** [comment]
https://dontkillmyapp.com/asus
Solutions are vendor specific.
