### ISSUE TITLE
Auto-force ID tags.

### ISSUE THREAD

**Issue by oddtoddy** [kawaiiDango/pScrobbler#82]
Hi, is there any way you would consider adding an auto-force option instead of having to hit "Force" button each time? I think this would be useful. Thanks!

**Comment by rxbrad** [comment]
Agree with this request. I'd like to scrobble podcasts from Podcast Addict, and every single one gets rejected and I have to manually force it.

**Comment by oddtoddy** [comment]
@rxbrad I've been using Simple Last.fm Scrobbler and it's been working well with Podcast Addict.

**Comment by kawaiiDango** [comment]
Artist searching has now been disabled except for youtube and browsers
