### ISSUE TITLE
[feature request] car interface to mark currently playing song as loved 

### ISSUE THREAD

**Issue by dgr7** [kawaiiDango/pScrobbler#83]
Hi, 
Would like to make a feature request of adding a Android Auto interface to the app so one could while driving and a song is playing that the app detects and is scribbling to switch to the pano scrobbler car interface and mark the song as loved.  Right now to do that you have to pick up the smartphone. 
https://developer.android.com/training/cars/media/automotive-os
Thanks!

**Comment by kawaiiDango** [comment]
Closing as I will not be implementing this
