### ISSUE TITLE
Network-related Problems Scrobbling

### ISSUE THREAD

**Issue by geneus** [kawaiiDango/pScrobbler#85]
First off, thanks for your work on this app, past and present. Appreciate the updates! 

My issue: Pano works incredibly offline. When I turn off all data connections, it saves scrobbles, then sends them when I connect (as advertised). 

When I listen to music, regardless of whether I'm using a mobile data connection or on Wi-Fi, say I play 4 albums (±2 hours worth of music), it will only scrobble 8, maybe 10 songs (or 30 minutes worth of songs). There's no obvious pattern as it will be random tracks from the various albums I was listening to.

As it stands, for every listening session with a data connection, I'm missing ¾ of my scrobbles. Eg. in the following screenshot, I was listening to Freeway on my desktop. Immediately started listening to other artists from my mobile. The scrobbled songs from Bruno Mars show an entire hour missing and I was listening to music all that time. Even with that, there are many songs it skipped from the time it captured my scrobbles. For both artists that were scrobbled, I played those albums from front to back but as you can see, it only scrobbled a few songs from each album.

![Screenshot_20200720-211211_Pano Scrobbler.jpg](https://user-images.githubusercontent.com/4223644/87978092-1e627a00-cad0-11ea-9cfb-7d06477f2b9f.jpg)

Initially thought my network was the issue but even after having upgraded to a relatively fast fibre connection, I still experience the same issue. Any idea what the issue could be?

**Comment by kawaiiDango** [comment]
Which player are you using?

**Comment by geneus** [comment]
Pano Scrobbler v1.88 - 03.Jul.20
Android 9 

Pardon the delay in responding.

**Comment by kawaiiDango** [comment]
That's not a player

**Comment by geneus** [comment]
Urgh! Read player but my brain thought you were asking what version of the app I'm using. 😑  My bad!

I use VLC for Android.

**Comment by kawaiiDango** [comment]
I couldn't reproduce this issue on vlc. Please send a bug report from the app shortly after reproducing this issue.
Also there was a bug in v1.88 affecting Android 9+ which would sometimes crash the app if you opened it, you were online and had pending scrobbles or loves. That has been fixed.

**Comment by geneus** [comment]
The app has never crashed for me at all. This is more of a nuisance than anything else. A workaround that I use is to turn of data connections when listening to music then upload offline scrobbles when I'm done. This is okay as I mostly don't use my phone when listening to music. 

Works fine but quite irritating whenever I forget to switch off data as it will end up scrobbling a small fraction of the songs I played. Oh well. ¯\_(ツ)_/¯ 

Ta!
