### ISSUE TITLE
Export edits doesn't work

### ISSUE THREAD

**Issue by bar0v** [kawaiiDango/pScrobbler#86]
When I try to back up settings and edits from app I only get an empty json file. Xiaomi Mi 9T, MIUI 12, Android 10

**Comment by kawaiiDango** [comment]
I cannot reproduce this and the logs you sent had no errors.

**Comment by bar0v** [comment]
Oh okay. I tried this on Sony Xperia XA1+ and it worked fine so I think it's problem of MIUI itself.
