### ISSUE TITLE
Apple music not scrobbling

### ISSUE THREAD

**Issue by duramato** [kawaiiDango/pScrobbler#87]
The app doesn't seem to be scrobbling apple music for me. It works for Spotify.
This on OxygenOS 10 (stock room), OnePlus 8

If I can provide other info that might help let me know.

**Comment by kawaiiDango** [comment]
Send a bug report while playing music

**Comment by duramato** [comment]
Bug report sent

**Comment by kawaiiDango** [comment]
It broadcasted only the track name and no artist or album name. This is insufficient for scrobbling. Apple music doesn't allow scrobbling on iOS either, so they might be doing something similar for Android.
