### ISSUE TITLE
Custom ListenBrainz is not saving state and not showing any message

### ISSUE THREAD

**Issue by RCAPDART** [kawaiiDango/pScrobbler#88]
Hi!

When I'm saving any account data in "Custom Listenbrainz server" - it showing "mark sign" that everything is OK (even if I put wrong data). 
But it is not saving any data - when I'm opening it again - form is empty.
Label under the account is still showing "login". And it is not working.

Could you, please, help me with this? May be I'm doing something wrong?

![image](https://user-images.githubusercontent.com/1285232/89414944-e005c580-d733-11ea-986e-cef9e4a626c5.png)

**Comment by kawaiiDango** [comment]
Login worked fine when I tested it and someone else who was able to login
just opened an issue about custom listenbrainz, so I guess you are just
using an old version of pano scrobbler.

**Comment by RCAPDART** [comment]
Hi! I used the latest version of the app from the Google Play.
And it is working fine with Simple Scrobbler.

**Comment by kawaiiDango** [comment]
Send a bug report from the app after you reproduce the bug

**Comment by RCAPDART** [comment]
I sent you bug report, sorry for the delay.

**Comment by kawaiiDango** [comment]
I think I broke it in the July update, so it was still working for people who logged in before July. It should be fixed when the update is out.

**Comment by RCAPDART** [comment]
It works fine now, thank you!
