### ISSUE TITLE
What does the scrobbler expect in response to a 'submit-listens' with type 'import'?

### ISSUE THREAD

**Issue by krateng** [kawaiiDango/pScrobbler#89]
My pano submits single scrobbles to a custom server without problem, but whenever scrobbles land in pending, it just endlessly repeats the request to scrobble them despite receiving a 200 response with the content `{"status":"ok","code":200}`. Is there anything the response json needs to contain for pano to see the request as successful?

**Comment by kawaiiDango** [comment]
>
>
> <https://github.com/kawaiiDango/pScrobbler/blob/39db32e8c5baaa2dd1e3c3a26c843207c6fbd11e/lastfm/src/main/java/de/umass/lastfm/scrobble/ScrobbleResult.java#L62>

It looks for {'status': 'ok'} as specified here
https://github.com/metabrainz/listenbrainz-server/blob/cd6946d9426334372dc314af1849f6c7596c9f9f/listenbrainz/webserver/views/api.py#L78

Works fine with my copy of listenbrainz server

>

**Comment by krateng** [comment]
Hm, I can't figure out why it doesn't work for me. Would it be possible to reduce the frequency of retrying to batch-scrobble to something like once every hour? Right now, Pano is eating a significant part of my mobile data usage with several requests per second.

**Comment by krateng** [comment]
Scratch that, I think it works now. Hope it stays that way :D Thanks for the help, closing this.

**Comment by kawaiiDango** [comment]
Please send a bug report from the app when this happens again
