### ISSUE TITLE
New User, Scrobler isn't Working For Me

### ISSUE THREAD

**Issue by darylf** [kawaiiDango/pScrobbler#90]
Hi there, 

I'm having a weird situation perhaps you can help with. I recently installed the app on my Pixel 3. I authorized Last.fm and Libre.fm to use the app, set the notification permission, and chose to Scrobble from Google Play and Youtube Music.

When playing from Google Play, the Pano notification identifies that it's going to scrobble my song. Libre.fm displays the "Now Playing", but Last.fm does not. When the song finishes, my Pano notification displays "Ignored scrobble" for Libre.fm, despite successfully scrobbling to Libre (but not Lastfm)

**Support Request:** What's happening here? Please help me fix m Last.fm (Is there logs I can provide, or more details I can offer).

**Feature Request:** Clicking the notification, I expected to get to an error page on the Pano app with some further details about what happened. Instead, it took me to the app and displayed my recent scrobbles.

**Comment by kawaiiDango** [comment]
Read the notification. It will say lastfm or librefm ignored the scrobble. It does not say pano scrobbler ignored the scrobble. Probably fix your tags.

**Comment by darylf** [comment]
Sorry, I think I didn't get my issue accros.
Here is a screenshot of my notification: https://imgur.com/a/qH87uJH

Again, there's no explanation of the error. It would be cool if I could tap that notification and be taken to a screen in Plano which provided some more details.

Something that's interesting is that it actually did scrobble to Libre.fm ([see here](https://libre.fm/user/MadCowDzz/recent-tracks)), but it didn't scrobble to Last.fm... Nothing has scrobbled to lastfm from Pano.

**Comment by darylf** [comment]
Something happened over the past 7 hours: my Last.fm scrobbles must have batched and eventually submitted successfully to Last.fm I guess there was some delay for some reason, although it's unclear what actually happened to me. 

From within the application, is there any way to see a list of the pending scrobbles?

**Comment by darylf** [comment]
Any idea what would cause Last.fm to not idsplay the album art once an item is scrobbled? The Now Playing item displays the album art, but once it's scrobbled the art goes away. Are you missing a value when things get sent? I'm using YouTube Music as the player.

Last.fm screenshot: https://imgur.com/a/qtwneMT

**Comment by darylf** [comment]
Everything seems to be functioning now, at least as ell as expected. I'll close this issue despite not really knowing what was wrong.

Thanks for your time on the app and keep up the great work! 👍
