### ISSUE TITLE
Fixes to the scrobbling logic have removed a nice little workaround for Podcast Addict

### ISSUE THREAD

**Issue by djryan** [kawaiiDango/pScrobbler#92]
Podcast Addict adds the date of the podcast to its notification, which gets picked up as part of the artist field.  Pausing or fast forwarding the podcast in the old code meant that PanoScrobbler reloaded this and it picked up the artist alone.

The latest change to code to pick up the notification seems to have removed this neat workaround, which means that every artist now contains the date regardless of whether it's paused or not.

Is it possible to make it easy to split the artist field to pick up a normal artist again?

**Comment by kawaiiDango** [comment]
It will now remove the date from the artist

**Comment by djryan** [comment]
❤️ You remain amazing!  Thanks so much.
