### ISSUE TITLE
Pano scrobbler doesn't scrobble when display is off

### ISSUE THREAD

**Issue by tavernhell** [kawaiiDango/pScrobbler#96]
Hello, I'm running the last version of the app on my Huawei P8 lite (up to date OS version). 

First of all, I wanted to say that on the first install I can't select the app after clicking Enable Autostart (the screen that appears is empty -> https://i.imgur.com/Mhl927Z.png). 

I'm trying to scrobble from PowerAMP, which scrobbled fine until 2 months ago. _If I keep the screen active the track successfully scrobbles_. If I turn the screen off and then on again, the PanoScrobbler notification icon is still there and it says "Song scrobbled" but it doesn't actually do that.

What I already tried: reinstalling the app, disable/enable notifications, but that didn't work.

**Comment by kawaiiDango** [comment]
Which Android version, emui version do you have?

**Comment by tavernhell** [comment]
> Which Android version, emui version do you have?

Both EMUI and Android version are 8.0.0

**Comment by kawaiiDango** [comment]
This is not a pano scrobbler issue. See dontkillmyapp.com

**Comment by tavernhell** [comment]
> This is not a pano scrobbler issue. See dontkillmyapp.com

Thanks, I've correctly set the permission for PS. I'll close the issue for now and eventually re-open it if that didn't solve the problem.
