### ISSUE TITLE
Can't scrobbe netease cloud music app

### ISSUE THREAD

**Issue by Vincentaria** [kawaiiDango/pScrobbler#97]
The latest version of pScrobbler cannot scrobe netease cloud music app, it shows "Couldn't parse title (Tap to edit)" , this app can be scrobbed without problem before, could you help to fix it? I'm using MIUI12 OS

Link of netease cloud music app:

https://play.google.com/store/apps/details?id=com.netease.cloudmusic

**Comment by kawaiiDango** [comment]
Parsing of title is only done for browsers, nicobox and YouTube. It can
only happen if the app is telling the system that it is a browser, and in
that case the app developers should fix the app. I wasn't able to test it
myself as the app seems to be banned in my country.

**Comment by Vincentaria** [comment]
Thank you for the fast reply.

The apk file can be downloaded from below link, I tried the official last.fm app and seems it can scrobbe it, I appreciate if you could help to look into it, thank you:)

https://apkpure.com/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90/com.netease.cloudmusic

**Comment by kawaiiDango** [comment]
I downloaded the apk and it seems to give some kind of error in Chinese when I open.
![Screenshot_20200930-213336__01.jpg](https://user-images.githubusercontent.com/1066519/94711069-44748800-0365-11eb-9ebc-43add7144caf.jpg)

The official lastfm app doesn't parse titles for browsers and that's why it scrobbles website addresses and Facebook.com is one of the trending artists on last.fm. Pano scrobbler avoids this.

**Comment by Vincentaria** [comment]
I think the previous link I sent is the old version, below link is the latest version 7.3.20, I can use it on MIUI and SAMSUNG tablet without problem.

https://www.coolapk.com/apk/com.netease.cloudmusic

**Comment by kawaiiDango** [comment]
Seems to work fine here for a cloud song. Is there a specific song that doesn't scrobble?
![Screenshot_20200930-222518__01.jpg](https://user-images.githubusercontent.com/1066519/94716113-0464d380-036c-11eb-8d77-d924d6ff4929.jpg)

**Comment by Vincentaria** [comment]
All songs (online and local) cannot be scrobbed, do you install and test the latest 7.3.2.0 version?
![IMG_20201001_024241](https://user-images.githubusercontent.com/60126910/94726692-2bcd9780-0390-11eb-9b21-974b729bd619.jpg)
![IMG_20201001_024257](https://user-images.githubusercontent.com/60126910/94726701-2ff9b500-0390-11eb-9d66-f38e0e780621.jpg)

**Comment by kawaiiDango** [comment]
Yes. It took time to update the browser list and I got the same thing. The app does tell the system that it is a browser
![Screenshot_20201001-005842__01.jpg](https://user-images.githubusercontent.com/1066519/94730902-94614800-0381-11eb-9718-152fe24d0f55.jpg)

**Comment by kawaiiDango** [comment]
Also noticed that the older apk wasn't a browser, this one is

**Comment by Vincentaria** [comment]
Is it possible to scrobbe this specific app without parsing titles, like the way official last.fm scrobbes? Or adding on/off function of parsing titles? As this is one of the most popular cloud music apps in China, I don't think they'll amend it per my request, sorry to trouble you again
